### PR TITLE
Add Front and Contains type list meta functions

### PR DESCRIPTION
**Pull request by bernhardmgruber**
As suggested by @BenjaminW3, this PR splits out the two added meta functions form the accessor PR #1249.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Could you please create a new file per function? They have nothing in common with the boolean metafunctions in this header.

**Comment by bernhardmgruber** [comment]
I think creating a new file per function is an overkill, since the funtions are really simple. However, there is no good existing place either. Metafunctions.hpp was the best existing choice IMO. What do other people think?

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
@bernhardmgruber Maybe we should move it into a separate file as @BenjaminW3  suggested. 
`meta/ListOp.hpp` or `meta/ListSearch.hpp`
How is the file in mp11 called?

**Comment by bernhardmgruber** [comment]
mp11 groups algorithms, as shown on the left side in their docs: https://www.boost.org/doc/libs/develop/libs/mp11/doc/html/mp11.html

I think for alpaka we could also have one header file containing type list operations. This header should include the content of `Apply.hpp`, `CartesianProduct.hpp`, `Concatenate.hpp`, `Filter.hpp`, `InheritFromList.hpp`, `Transform.hpp` and `Unique.hpp`. Maybe `TypeList.hpp` or `TypeListOps.hpp` is a good name.

We could also have a dedicated type list template, so `Accessor` does not need to use `std::tuple` for the access mode tag list.

**Review by psychocoderHPC — DISMISSED** [review]

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
