### PR TITLE
Fixes alpaka logo (removes white color in ear).

### PR DESCRIPTION
**Pull request by tdd11235813**
There is a white filled space in the ear to hide the path in behind. This becomes visible on non-white backgrounds.
This removes the filling and the piece of path in behind. Alpaka logo png-file not updated, because it is all white.
Edit: stopped travis CI test, as this does not touches any code.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Without a CI build it can not be merged. I will restart it.

**Review by BenjaminW3 — APPROVED** [review]

**Comment by tdd11235813** [comment]
oh ok, thanks, thought it was possible to ignore it somehow.

**Comment by ax3l** [comment]
For such changes, you can write `[skip travis]`, `[skip ci]`, etc. somewhere in your commit message: https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by BenjaminW3** [comment]
But even with the flag in the commit message github does not allow an exception to the merge rule that enforces a green build.

**Comment by ax3l** [comment]
oh, good to know.
(but repo admins can overwrite if one allows it ;) )

**Pull request merged**
