### PR TITLE
Make mangled CUDA kernel name as short as possible

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This PR aims to make the mangled name of CUDA kernels launched by alpaka as short as possible and places the name of the kernel functor at the front of the template argument list, so it is more easily found in a profiler.

Example:
image

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
I welcome suggestions for a better name and place instead of `alpaka::detail::kernel`, but please aim for making it short!

**Comment by j-stephan** [comment]
I'm a bit afraid that this will collide with similar changes for the other back-ends. What happens when we put the OpenMP kernels into `alpaka::detail`, too?

**Comment by bernhardmgruber** [comment]
> I'm a bit afraid that this will collide with similar changes for the other back-ends. What happens when we put the OpenMP kernels into `alpaka::detail`, too?

Well, you will get an error in the unit tests then. And then you will either have to choose a new name for the OpenMP entity, or rename the CUDA/HIP kernel entry point. But we can do all of that since we are in the detail namespace.

Do you have a better suggestion for a short mangled name?

**Comment by j-stephan** [comment]
I do not. However, I believe my fears are unfounded. The alpaka kernel object that is passed to the actual kernel in `alpaka::detail` should have the chosen Accelerator as part of its template instantiation. So even if we pass a kernel to both OpenMP and CUDA the instantiated objects should still be different.

**Comment by psychocoderHPC** [comment]
What do you think about calling the CUDA/HIP kernel `alpaka::detail::gpuKernel` to avoid naming collision and later we could name OMP kernel `alpaka::detail::omp2BlockKernel`, `alpaka::detail::omp2ThreadKernel`, `alpaka::detail::serialKernel` `alpaka::detail::omp5Kernel`, ... if needed.

**Comment by fwyzard** [comment]
What about `alpaka::kernel::gpu`, `alpaka::kernel::omp2Block`, _etc._ ?

**Comment by fwyzard** [comment]
Though `gpu` is maybe a bit too generic, assuming the SYCL/oneAPI kernels use a different entry point ?

**Comment by bernhardmgruber** [comment]
Ok, I will rename it to `alpaka::detail::gpuKernel`.

> What about alpaka::kernel::gpu, alpaka::kernel::omp2Block, etc. ?

These names would work as well. However, I prefer using the detail namespace as it also intentionally communicates that we do not promise the name `gpuKernel` or the existence of a namespace `kernel`.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
