### PR TITLE
[WIP] remove workaround for broken `hipStreamAddCallback`

### LINKED ISSUE #794: HIP(HCC) queue and time test failures
- compiling time test fails for `--amdgpu-target=gfx701` (just remove it in alpakaConfig.cmake)
- queue test `queueShouldNotExecuteTasksInParallel` fails at runtime (tested on AMD RX Vega64, fwk388)

```zsh
-------------------------------------------------------------------------------
queueShouldNotExecuteTasksInParallel
-------------------------------------------------------------------------------
/alpaka/test/unit/queue/src//QueueTest.cpp:184
...............................................................................

/alpaka/test/unit/queue/src//QueueTest.cpp:132: FAILED:
  CHECK( !taskIsExecuting.exchange(true) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:134: FAILED:
  CHECK( taskIsExecuting.exchange(false) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:144: FAILED:
  CHECK( !taskIsExecuting.exchange(true) )
with expansion:
  false

/alpaka/test/unit/queue/src//QueueTest.cpp:146: FAILED:
  CHECK( taskIsExecuting.exchange(false) )
with expansion:
  false

===============================================================================
test cases:  5 |  4 passed | 1 failed
assertions: 40 | 36 passed | 4 failed
```

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #794

Remove workaround introduced in #800

- re-enabled queue test for the non blocking HIP queue
- remove workaround (polling and mutex)
- increase required HIP version to 3.0
- update documentation

Note: 
- we forgot to increase the HIP version to 2.8 for 'hipMemcpy3Dasync`
- hipMemcpy3D is broken https://github.com/ROCm-Developer-Tools/HIP/issues/1790 should be solved with the next HIP release 3.1 - AMD is working on a [fix](https://github.com/ROCm-Developer-Tools/HIP/pull/1798)

- [ ] do not merge we need to wait for #928

### CODE REVIEW

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by ax3l** [comment]
@psychocoderHPC In order to avoid inconsistencies, don't forget to update the HIP version documented in `README.md`.

**Comment by psychocoderHPC** [comment]
I updated the README and documentation

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by tdd11235813** [comment]
is the `hipStreamAddCallback` fixed or is it still broken? It's not clear to me why the workaround can be removed.

**Comment by psychocoderHPC** [comment]
> is the `hipStreamAddCallback` fixed or is it still broken? It's not clear to me why the workaround can be removed.

It looks like the issue is fixed in HIP, as you can see I [re-enabled the test](https://github.com/ComputationalRadiationPhysics/alpaka/pull/927/files#diff-8e3c2a38eb4e69ca9e53c39d198bd9e6L41) and all works fine.

**Comment by BenjaminW3** [comment]
You have to change the `ALPAKA_CI_HIP_BRANCH="roc-2.8.0"` in `.travis.yml` to use the newer version. CI complains because you now request 3.0 minimum.

**Comment by tdd11235813** [comment]
@psychocoderHPC which ROCm/HCC version do you take? I know hcc is deprecated, but the workaround was only for hip/hcc. hip-clang was not ready at that time. 
Maybe I need your local test setup for the environment, because I get compile errors:
```
/alpaka/include/alpaka/math/abs/AbsHipBuiltIn.hpp:28:18: fatal error: 'math_functions.h' file not found
        #include <math_functions.h>
```
I have used (fwk388)
```sh
 spack load cmake@3.15.1
 spack load boost@1.68.0
 export ROCM_PATH=/opt/rocm
 export HIP_PATH=${ROCM_PATH}/hip
 export HCC_HOME=$ROCM_PATH/hcc
 export HIP_PLATFORM=hcc
 export HIP_RUNTIME=hcc
```

**Comment by psychocoderHPC** [comment]
> math_functions.h

The include must be `hip/math_functions.h` instead of `math_functions.h`. I am wondering why it worked before. I was on the way to fix it but since it is working in the current tests I keep it as it is. 
I will fix this in a separate PR but we have currently a few conflicting PR's so I like to have #928 first in to avoid that @jkrude must rebase to often. His PR is to complex and I would like to avoid that we invest to much time into rebasing.

workaround: Set `export CPLUS_INCLUDE_PATH=$HIP_PATH/include:$HIP_PATH/include/hip` on fwk388 for now.

**Comment by psychocoderHPC** [comment]
@tdd11235813 please do not test hcc, please use hip-clang. When the cmake refactoring and the unification of HIP and CUDA is in I will remove the support for HIP-hcc

use:

```sh
export HIP_PATH=/opt/rocm
export HIP_PLATFORM=clang
export HIP_CLANG_PATH=$HIP_PATH/llvm/bin
export DEVICE_LIB_PAT=$HIP_PATH/llvm/lib
export PATH=$HIP_PATH/bin:$HIP_PATH/llvm/bin:$HIP_PATH/rocprofiler/bin:$PATH

export CC=$HIP_CLANG_PATH/clang
export CXX=$HIP_CLANG_PATH/clang++
```
Edit(tdd11235813): HIP_PATH: removed `$`

**Comment by tdd11235813** [comment]
thanks for the setup. The workaround is still required, I still get errors in the queue test, when the workaround is removed.

**Comment by tdd11235813** [comment]
... my setup:
```sh
spack load cmake@3.15.1  
spack load boost@1.68.0  

export HIP_PLATFORM=clang                                                                                       
export HIP_PATH=/opt/rocm/hip                                                                                   
export ROCM_PATH=/opt/rocm                                                                                      
export LD_LIBRARY_PATH=$ROCM_PATH/roctracer/lib/:$ROCM_PATH/rocprofiler/lib:${HIP_PATH}/lib64:${LD_LIBRARY_PATH}
export CMAKE_PREFIX_PATH=${HIP_PATH}:${BOOST_ROOT_DIR}:${CMAKE_PREFIX_PATH:-}                                   
export DEVICE_LIB_PATH=/opt/rocm/lib                                                                            
export CPLUS_INCLUDE_PATH=/opt/rocm/llvm/hip/include/hip/:/opt/rocm/hiprand/include/:/opt/rocm/rocrand/include  
export HIP_CLANG_PATH=/opt/rocm/llvm/bin                                                                        
export PATH=$ROCM_PATH/bin:$PATH:$HIP_CLANG_PATH                                                                
                                                                                                                
cmake -DCMAKE_CXX_COMPILER=clang++ \                                                                            
      -DALPAKA_HIP_PLATFORM=clang \                                                                             
      -DALPAKA_ACC_GPU_HIP_ENABLE=ON \                                                                          
      -DALPAKA_ACC_GPU_HIP_ONLY_MODE=ON \                                                                       
      -DALPAKA_ACC_GPU_CUDA_ENABLE=OFF \                                                                        
      -DHIP_PLATFORM=clang \                                                                                    
      -DALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=OFF \                                                              
      ..                                                                                                        
                                                                                                                
make queue                                                                                                      
./test/unit/queue/queue                                                                                         
```

(make showed: `/opt/rocm/llvm/bin/clang++` for compiling)

**Comment by psychocoderHPC** [comment]
Do not merge this PR I like to have #928 in, else we get rebase issues in #928

**Comment by psychocoderHPC** [comment]
> ... my setup:
> 
> ```shell
> spack load cmake@3.15.1  
> spack load boost@1.68.0  
> 
> export HIP_PLATFORM=clang                                                                                       
> export HIP_PATH=/opt/rocm/hip                                                                                   
> export ROCM_PATH=/opt/rocm                                                                                      
> export LD_LIBRARY_PATH=$ROCM_PATH/roctracer/lib/:$ROCM_PATH/rocprofiler/lib:${HIP_PATH}/lib64:${LD_LIBRARY_PATH}
> export CMAKE_PREFIX_PATH=${HIP_PATH}:${BOOST_ROOT_DIR}:${CMAKE_PREFIX_PATH:-}                                   
> export DEVICE_LIB_PATH=/opt/rocm/lib                                                                            
> export CPLUS_INCLUDE_PATH=/opt/rocm/llvm/hip/include/hip/:/opt/rocm/hiprand/include/:/opt/rocm/rocrand/include  
> export HIP_CLANG_PATH=/opt/rocm/llvm/bin                                                                        
> export PATH=$ROCM_PATH/bin:$PATH:$HIP_CLANG_PATH                                                                
>                                                                                                                 
> cmake -DCMAKE_CXX_COMPILER=clang++ \                                                                            
>       -DALPAKA_HIP_PLATFORM=clang \                                                                             
>       -DALPAKA_ACC_GPU_HIP_ENABLE=ON \                                                                          
>       -DALPAKA_ACC_GPU_HIP_ONLY_MODE=ON \                                                                       
>       -DALPAKA_ACC_GPU_CUDA_ENABLE=OFF \                                                                        
>       -DHIP_PLATFORM=clang \                                                                                    
>       -DALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=OFF \                                                              
>       ..                                                                                                        
>                                                                                                                 
> make queue                                                                                                      
> ./test/unit/queue/queue                                                                                         
> ```
> 
> (make showed: `/opt/rocm/llvm/bin/clang++` for compiling)

Mhhh you are right, I tested it before and it was working without issue. I will have a look into it. IN the worst case I will remove the callback feature for the HIP backend. The problem is the workaround with the events is not usable if you like to use it in a real world example.

@tdd11235813 Thanks for testing it again.

**Comment by psychocoderHPC** [comment]
The HIP requirements was updated with #939 and the polling workaround will be removed in a separate PR by dropping HIP-hcc  support

**Pull request closed without merging**
