### PR TITLE
Add another CUDA windows build (release + mixed backends)

### LINKED ISSUE #541: Add CI support for CUDA on Windows
I have successfully build alpaka with Visual Studio 2017.7 and CUDA 9.2 (even though this is an unsupprted version and I had to change the `host_config.h` file).
However, we can not state that we support this combination as long as we have no continuous integration testing it. Therefore, we have to add CUDA installation and compilation to the Appveyor CI.

### PR DESCRIPTION
**Pull request by BenjaminW3**
Fixes #541

### CODE REVIEW

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
@BenjaminW3 Is the broken test hitting the travis walltime limit?

**Comment by BenjaminW3** [comment]
Seems to be the case...
I will disable one more CPU backend.

**Comment by ax3l** [comment]
Still seems to take to long. Maybe build it in `Release` mode?

**Comment by BenjaminW3** [comment]
`Release` mode was what I tried before ;-)

**Comment by psychocoderHPC** [comment]
@BenjaminW3 We are working on new CI scripts. The pain will have hopefully soon an end. But until that we need to workaround the memory issues :-(

**Comment by BenjaminW3** [comment]
I was able to resolve the compilation time issue by using 2 threads for compilation.
This is ready to be merged now!

**Comment by BenjaminW3** [comment]
Please approve

**Review by sbastrakov — APPROVED** [review]

**Pull request merged**
