### PR TITLE
gitignore: more IntelliJ/KDevelop

### PR DESCRIPTION
**Pull request by ax3l**
Add more typical files/dirs created by IntelliJ IDEs (CLion) and Kdevelop.

Related to #921

### CODE REVIEW

**Comment by bertwesarg** [comment]
Instead of chasing down all your cloned Git repos to update the `.gitignore` to fit your environment, why not just update your environment to fit itself:

https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreexcludesFile

**Comment by sbastrakov** [comment]
@bertwesarg I feel having personal global git settings is definitely useful, however, we should not rely on everyone having it and so should provide reasonable  repository-level ignore settings.

**Review by BenjaminW3 — APPROVED** [review]

**Comment by bertwesarg** [comment]
I don't think you do users a favor if you provide them these defaults. Because not all repos will have these in the `.gitignore` list. So at some point they will need to find another solution anyway. You do them a favor by educate them to use their global ignore list in the first place:

```diff
diff --git i/.gitignore w/.gitignore
index b8633b2ee..2fa2295e3 100644 .gitignore
--- i/.gitignore
+++ w/.gitignore
@@ -2,22 +2,18 @@
 !/doc/doxygen/Doxyfile
 !/doc/doxygen/alpaka_doxygen.png
 /doc/latex/*
-**/build
 
 # tmp files
 *~
 
-# netbeans project files
-/nbproject/
-
-# Code::Blocks project files
-/*.cbp
-/*.layout
-
 # original backup files
 *.orig
 
-# VIM project files
-.vimrc
-
-.idea/
+# Please consider adding ignore patterns of IDE related or tmp build directories to
+# your global ignore file. This way they apply to all of your local repositories.
+#
+# See
+#
+#     https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreexcludesFile
+$
+# for instructions how to do it. Thanks.
```

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
> I don't think you do users a favor if you provide them these defaults. Because not all repos will have these in the `.gitignore` list. So at some point they will need to find another solution anyway. You do them a favor by educate them to use their global ignore list in the first place:
> 
> ```diff
> diff --git i/.gitignore w/.gitignore
> index b8633b2ee..2fa2295e3 100644 .gitignore
> --- i/.gitignore
> +++ w/.gitignore
> @@ -2,22 +2,18 @@
>  !/doc/doxygen/Doxyfile
>  !/doc/doxygen/alpaka_doxygen.png
>  /doc/latex/*
> -**/build
>  
>  # tmp files
>  *~
>  
> -# netbeans project files
> -/nbproject/
> -
> -# Code::Blocks project files
> -/*.cbp
> -/*.layout
> -
>  # original backup files
>  *.orig
>  
> -# VIM project files
> -.vimrc
> -
> -.idea/
> +# Please consider adding ignore patterns of IDE related or tmp build directories to
> +# your global ignore file. This way they apply to all of your local repositories.
> +#
> +# See
> +#
> +#     https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreexcludesFile
> +$
> +# for instructions how to do it. Thanks.
> ```

I added the issue #936 to discuss this.

**Comment by ax3l** [comment]
> I don't think you do users a favor if you provide them these defaults. Because not all repos will have these in the .gitignore list.

I don't follow. If you clone a git repo, you will get its `.gitignore`.

**Pull request merged**
