### PR TITLE
Fix `isValidWorkDivKernel` to use the correct device

### PR DESCRIPTION
**Pull request by fwyzard**
Currently `isValidWorkDivKernel` does not use the device passed as an argument to determine the kernel properties: instead, it creates a new device taking the first one from the accelerator platform.

This can have two problems:
  - the devices in the accelerator platform may have different properties; for example, one can have two different NVIDIA GPUs in the same machine (_e.g._ a V100 and an L4) that lead to  different kernel attributes; checking the attributes from one GPU and running on the other may give unexpected results.
  - some platforms (_e.g._ SYCL) have stateful device objects, so it's better not to create a new one every time.

The fix is to use the device that is passed as an argument to query the kernel attributes.

### CODE REVIEW

**Comment by fwyzard** [comment]
@mehmetyusufoglu can you review this PR ?

**Comment by fwyzard** [comment]
By the way, since we have `getValidWorkDivForKernel`, would it make sense to rename `isValidWorkDivKernel` to `isValidWorkDivForKernel` ?

**Comment by mehmetyusufoglu** [comment]
Yes it is renamed. The old one remains.

31 Tem 2024 Çar 10:22 tarihinde Andrea Bocci ***@***.***>
şunu yazdı:

**Comment by mehmetyusufoglu** [comment]
> @mehmetyusufoglu can you review this PR ?

Yes, you are right GetFunctionAttributes and GetDeviceProperties should use the same device.

**Comment by psychocoderHPC** [comment]
> By the way, since we have `getValidWorkDivForKernel`, would it make sense to rename `isValidWorkDivKernel` to `isValidWorkDivForKernel` ?

IMO good idea, currently we can do such changes be cause the interface is very new anyway.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
