### PR TITLE
backport to 0.6.1

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Backport to 0.6.1:
- fix static shared memory alignment #1282
- Fix BlockSharedMemStMemberImpl::getVarPtr for last var #1280
- Rework implementation of OpenMP schedule support #1279
- fix CtxBlockOacc: SyncBlockThreads #1291
- port macOSX CI fix from #1283

The CHANGELOG.md file is updated too.

**Note:** This PR will be merged into branch 0.6.1.

### CODE REVIEW

**Review by j-stephan — DISMISSED** [review]

**Comment by j-stephan** [comment]
Looks like some stuff for the OpenMP scheduling is missing? The CI instances fail after a few minutes because of this.

**Comment by psychocoderHPC** [comment]
> Looks like some stuff for the OpenMP scheduling is missing? The CI instances fail after a few minutes because of this.

I forgot to cherry-pick one commit. CI is now testing again.

**Comment by j-stephan** [comment]
Still failing with a rather amusing message:

```
/home/runner/work/alpaka/alpaka/include/alpaka/core/OmpSchedule.hpp:101:22: error: no newline at end of file [-Werror,-Wnewline-eof]
} // namespace alpaka
                     ^
1 error generated.
```

**Comment by sbastrakov** [comment]
The #1291 fix should also go here, after it's merged?

**Comment by psychocoderHPC** [comment]
> The #1291 fix should also go here, after it's merged?

I will port it in a separate PR.

**Comment by psychocoderHPC** [comment]
**IMPORTANT**  
I added a commit that only pulls the fix for the macOSX CI from #1283.
Additionally, I already included #1291 because I am touching this PR anyway.

CC-ing: @jkelling #1291 will be soon testable with alpaka 0.6.1.

**Comment by psychocoderHPC** [comment]
> The #1291 fix should also go here, after it's merged?

#1291 is now included, the reason is one comment above.

**Comment by psychocoderHPC** [comment]
@alpaka-group/alpaka-maintainers CI is giving green light!

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
