### PR TITLE
Test installation in CI

### LINKED ISSUE #1487: Installation is broken
The PR #1456 removed the directory "cmake/modules", which is still referenced in `CMakeLists.txt` for installation alpaka. This makes the installation fail. See e.g. LLAMA CI: https://github.com/alpaka-group/llama/runs/4365043305?check_suite_focus=true

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Tests installation as part of the CI.

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
Just a question, the CI test only the installation of alpaka. It does not use the installed alpaka?

**Comment by bernhardmgruber** [comment]
> Just a question, the CI test only the installation of alpaka. It does not use the installed alpaka?

Correct. The CI now just runs the install target after building.

**Comment by j-stephan** [comment]
@bernhardmgruber In the future, would you kindly set the appropriate labels, project(s) and linked issues in the side bar? This makes project management much easier for me.

**Comment by bernhardmgruber** [comment]
I really enjoyed you doing that :) But sure, I can try to do it myself then!

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
