### PR TITLE
Add clang-17 to CI

### LINKED ISSUE #2169: Add support for clang-17
LLVM 17 was just released: https://discourse.llvm.org/t/llvm-17-0-1-released/73549

Let's add support for clang-17 to the CI.

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Includes: #2171 

Fixes: #2169

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Ah, seems I pushed the branch to the wrong remote. Sorry about that!

**Comment by bernhardmgruber** [comment]
Alright, I somehow lost connection to the GitLab CI. I am reopening the PR here: #2174

**Comment by j-stephan** [comment]
Interesting, the GitHub UI still shows a `clang17` branch on the main repository page. Did you delete some other branch here?

**Comment by bernhardmgruber** [comment]
> Interesting, the GitHub UI still shows a `clang17` branch on the main repository page. Did you delete some other branch here?

I have no idea :D I intended to delete the one I accidentially created. I deleted it manually now.

**Pull request closed without merging**
