### PR TITLE
Reserve the devices vector memory before filling it

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
By the way, I have related question: does Alpaka guarantee that
```c++
alpaka::getNativeHandle(alpaka::getDevByIdx<TPlatform>(i)) == i
```
?

I guess "no", since _e.g._ for the SYCL back-ends `alpaka::getNativeHandle()` returns something more complex than an `int`.

Is there any way to retrieve the index that a device has inside the `vector` returned by `alpaka::getDevs<TPltf>()` ?

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
As you wrote a native handle can be an arbitrary object and is only on some platforms an index.

> Is there any way to retrieve the index that a device has inside the vector returned by alpaka::getDevs<TPltf>() ?

As I know currently not. Let me link here your corresponding issue: #1927

**Comment by psychocoderHPC** [comment]
The CI is failing because we have a new GPU in the CI node with a gfx1030. We need to silence the warning for clang.
I try to look into this issue this week.

```
/opt/rocm-5.2.0/include/rocrand/rocrand_common.h:73:6: error: "Disabled inline asm, because the build target does not support it." [-Werror,-W#warnings]
    #warning "Disabled inline asm, because the build target does not support it."
     ^
1 error generated when compiling for gfx1030.
```

**Comment by fwyzard** [comment]
Adding `-Wno-error=#warnings` to the clang/hipcc command line should do it.

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
I opened PR #1932 to hopefully silence the error for HIP <= 5.3

**Comment by psychocoderHPC** [comment]
@fwyzard Could you please rebase this PR against the latest dev, #1932
 is merged and the CI is working again.

**Comment by fwyzard** [comment]
> @fwyzard Could you please rebase this PR against the latest dev, #1932 is merged and the CI is working again.

done

**Review by bernhardmgruber — APPROVED** [review]

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
