### PR TITLE
Avoid locking for atomic operation on simple types

### LINKED ISSUE #1452: Mutex in atomic operation increases contention and reduces performance
When running our pixeltrack-standalone benchmark with the tbb backend we noticed that the tbb backend performance does not scale with the number of threads:

image

By profiling we realized that most of the time is spent waiting for this lock to be released:
https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/atomic/AtomicStdLibLock.hpp#L89-L90

This mutex could be replaced by atomic operations when working with simple types.

### PR DESCRIPTION
**Pull request by fwyzard**
This pull request is an attempt to solve the issue #1452. It is an updated and rebased version of #1453.

For Trivially Copyable types, aligned with `boost::atomic_ref<T>::required_alignment`, I specialized atomic operations to avoid locking. In the case in which atomics are often used to increase a counter, this may be beneficial.

For all feedback, discussion, evaluation of the performance,_etc._, please see #1453.

### CODE REVIEW

**Comment by fwyzard** [comment]
The only failing CI test is `windows_cl-2019_debug_analysis`, which complains about
```
2022-01-10T19:48:02.1645441Z LINK : fatal error LNK1104: cannot open file 'libboost_atomic-vc142-mt-gd-x64-1_74.lib' [D:\a\alpaka\alpaka\build\test\analysis\headerCheck\headerCheckTest.vcxproj]
```

However, both `windows_cl-2019_release` and `windows_cl-2019_debug` build and run all tests without issues.
What does the "analysis" build do differently ?

**Comment by fwyzard** [comment]
Mhm... the error looks the same:
```
2022-01-11T17:53:12.9499356Z LINK : fatal error LNK1104: cannot open file 'libboost_atomic-vc142-mt-gd-x64-1_74.lib' [D:\a\alpaka\alpaka\build\test\analysis\headerCheck\headerCheckTest.vcxproj]
```
but the library was built:
```
2022-01-11T17:42:48.3206203Z msvc.archive bin.v2\libs\atomic\build\msvc-14.2\debug\address-model-64\link-static\threading-multi\libboost_atomic-vc142-mt-gd-x64-1_74.lib
2022-01-11T17:42:48.3731786Z common.copy D:aalpakaalpaka\boost_libs\lib\libboost_atomic-vc142-mt-gd-x64-1_74.lib
2022-01-11T17:42:48.3874851Z bin.v2\libs\atomic\build\msvc-14.2\debug\address-model-64\link-static\threading-multi\libboost_atomic-vc142-mt-gd-x64-1_74.lib
2022-01-11T17:42:48.3876816Z         1 file(s) copied.
```

Do I need to add some linker flags as well ?

**Comment by j-stephan** [comment]
Yes, sorry. The CMake script also needs to be updated. I have created a PR for this PR: https://github.com/fwyzard/alpaka/pull/1

**Comment by fwyzard** [comment]
> Yes, sorry. The CMake script also needs to be updated. I have created a PR for this PR: [fwyzard#1](https://github.com/fwyzard/alpaka/pull/1)

Thanks !

**Comment by fwyzard** [comment]
Mhm, this is now running into some (other) problems:
  - the `linux_icpc_release` test fails because Boost B2 is unable to find `icpc` and/or understand the `icc` toolset:
    ```
    2022-01-11T20:15:58.3637421Z +++ eval 'sudo ./b2 -j1 --layout=tagged --toolset=icc architecture=x86 address-model=64 link=static threading=multi runtime-link=shared variant=release --with-fiber --with-context --with-thread --with-atomic --with-system --with-chrono --with-date_time cflags="-fPIC" cxxflags="-fPIC -std=c++17" --stagedir=/home/runner/work/alpaka/alpaka/boost_libs stage'
    2022-01-11T20:15:58.3640157Z sudo ./b2 -j1 --layout=tagged --toolset=icc architecture=x86 address-model=64 link=static threading=multi runtime-link=shared variant=release --with-fiber --with-context --with-thread --with-atomic --with-system --with-chrono --with-date_time cflags="-fPIC" cxxflags="-fPIC -std=c++17" --stagedir=/home/runner/work/alpaka/alpaka/boost_libs stage
    2022-01-11T20:15:58.3642883Z ++++ sudo ./b2 -j1 --layout=tagged --toolset=icc architecture=x86 address-model=64 link=static threading=multi runtime-link=shared variant=release --with-fiber --with-context --with-thread --with-atomic --with-system --with-chrono --with-date_time cflags=-fPIC 'cxxflags=-fPIC -std=c++17' --stagedir=/home/runner/work/alpaka/alpaka/boost_libs stage
    2022-01-11T20:15:58.4428971Z sh: 1: icpc: not found
    2022-01-11T20:15:58.4434491Z icc.jam: No such file or directory
    2022-01-11T20:15:58.4435179Z /home/runner/work/alpaka/alpaka/boost/tools/build/src/build/toolset.jam:44: in toolset.using
    2022-01-11T20:15:58.4435871Z ERROR: rule "icc.init" unknown in module "toolset".
    ```
  - the CL-2019 Windows builds correctly determine to build Boost (including Boost.Atomic), but somehow fail to install the built libraries, or to detect them while Alpaka runs CMake. 
  - the CUDA-only Windows builds fail because they (correctly) do not build Boost, but (incorrectly) require Boost.Atomic.

I can try to fix the last one, but I have no idea how to deal with the first two :-(

**Comment by fwyzard** [comment]
> * the `linux_icpc_release` test fails because Boost B2 is unable to find `icpc` and/or understand the `icc` toolset: ...

OK, I think I fixed the use of the wrong toolset, and I think the reason `icpc` is not found is because the Intel environment is set for the current user, but is not available for command run under `sudo`.
So `sudo ./b2 ...` does not find `icpc` :-(

**Comment by fwyzard** [comment]
OK, I had to rework a bit the installation of boost in the CI to support the installation of the intel compiler, but finally all checks are green :heavy_check_mark:

**Review by j-stephan — DISMISSED** [review]

**Comment by j-stephan** [comment]
Okay, this looks good to me. But I think you need to rebase onto the current `develop` since GitHub shows some conflicts.

However, since this introduces a new runtime dependency with Boost.Atomic I'd like to get some other opinions on this PR @alpaka-group/alpaka-maintainers. Maybe we need to switch the default values (i.e. use the lock-based atomics by default and only switch to Boost.Atomic by explicit user demand).

**Comment by fwyzard** [comment]
Rebased.

**Comment by fwyzard** [comment]
```
The install of cmake.install was NOT successful.
cmake.install not installed. An error occurred during installation:
 The remote server returned an error: (500) Internal Server Error. Internal Server Error
```

This is starting to become annoying...

**Review by bernhardmgruber — APPROVED** [review]

**Comment by j-stephan** [comment]
@bernhardmgruber I intentionally didn't merge this last week. We still need to discuss whether to use lock-based or boost-based atomics by default.

**Comment by bernhardmgruber** [comment]
I see. Then please add an unchecked checkbox to the PR description (first comment) next time, request changes (review) or turn the PR into a draft PR. Since you requested a review from me I figured I should review and take over.

**Comment by j-stephan** [comment]
I requested a review from all alpaka maintainers and explained this in my last comment... but in the future I will convert PRs like these to a draft.

**Comment by bernhardmgruber** [comment]
Ok, I seemed to have missed that. Sorry!

**Comment by fwyzard** [comment]
> but in the future I will convert PRs like these to a draft.

wouldn't that prevent the CI from running ?

**Comment by j-stephan** [comment]
Hm, that would be news to me. #1458 for example seems to run the CI. But then again I'm not the one who set up the CI rules so I'd have to investigate this first...

**Comment by fwyzard** [comment]
I don't know, I'm just asking (it works like that for the CMS software, but it's a completely different system)

**Pull request merged**
