### PR TITLE
Demangle the kernel names in the integration tests

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Comment by fwyzard** [comment]
> The following tests FAILED:
>	  3 - heatEquation (Timeout)

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by bernhardmgruber** [comment]
Please rebase to resolve the conflict! Thx!

**Review by bernhardmgruber — CHANGES_REQUESTED** [review]
@fwyzard I rebased your commit, but it seemed that broke your signature. I will let you do the rebase again and sign the commit appropriately!

**Comment by fwyzard** [comment]
Done !

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
