### PR TITLE
Make memcpy and memset operations for QueueCudaRtBlocking blocking async

### LINKED ISSUE #851: cudaMemset is not blocking
Related to issue #850 the [cuda documentation for cudaMemset](https://docs.nvidia.com/cuda/cuda-runtime-api/api-sync-behavior.html#api-sync-behavior__memcpy-sync) is saying 

```
Memset
The synchronous memset functions are asynchronous with respect 
to the host except when the target is pinned host memory or a 
Unified Memory region, ...
```

This means calling `cudaMemset` to NON pinned or managed memory and directly after call a kernel which works with the date within another stream (unrelated if we created the stream with `cudaStreamNonBlocking`) we will have the possibility of a data race.

[update] I added NON into my sentence because as @sbastrakov pointed out it is safe to use cudaMemSet for pinned memory but not for NON pinned.

### PR DESCRIPTION
**Pull request by BenjaminW3**
Hopefully fixes: #851, #850 and #504

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@BenjaminW3 thx for taken over and add the fixes. We need to do the same for hip(hcc/clang/nvidia) but we should do it in a separate PR.
I will test this PR against #850.

**Comment by psychocoderHPC** [comment]
We need to apply these changes to HIP too because HIP-nvcc will definitively show the same behavior.
I need to check if HIP-clang is also effected.

**Comment by psychocoderHPC** [comment]
I was on the way to add a test case, but this would require a few refactorings within our test helpers. We need to be able to select a `Blocking` queue for an accelerator. The current workflow within tests is to get the default queue this is a non blocking queue if debug is disabled else the blocking queue.
A test based on the example from #850 would not guarantee that we trigger the data race, therefore, it is  maybe also not the best test case.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
My manual tests showed that the bug is fixed.

**Comment by BenjaminW3** [comment]
I will try to apply this to HIP as soon as I find time.

**Pull request merged**
