### PR TITLE
Drop Accessor

### LINKED ISSUE #1897: Remove `experimental::Accessor`
We added `alpaka::experimental::Accessor` and some related classes to support SYCL as a backend for SYCL versions without pointers to device memory on the host (USM). Since #1482 was merged, this functionality can just as well be provided by `std::mdspan`. Furthermore, work is currently ongoing on reengineering the SYCL backend to require USM and thus also make `alpaka::experimental::Accessor` obsolete. See #1845.

Depending on whether USM will be required for the SYCL backend, we may need to add specializations for `alpaka::GetMdspan` to create `mdspan`s from SYCL buffers/accessors, or it may just work out of the box with USM pointers. In both cases, `alpaka::experimental::Accessor` is no longer required.

I would suggest we wait for the USM reengineering to finish and then remove `alpaka::experimental::Accessor`.

Depends on:

- [x] #1845

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #1897

### CODE REVIEW

**Review by j-stephan — APPROVED** [review]

**Comment by fwyzard** [comment]
This PR breaks the SYCL/oneAPI back-end.

**Comment by j-stephan** [comment]
Could you clarify? Do you see compilation errors?

I hope to get the PR for oneAPI CI jobs done today, then we won't keep facing these issues in the future.

**Comment by bernhardmgruber** [comment]
@fwyzard: sorry about that!
@j-stephan: much appreciated!

**Comment by fwyzard** [comment]
> Could you clarify? Do you see compilation errors?

```
/home/fwyzard/src/alpaka-group/alpaka/include/alpaka/kernel/TaskKernelGenericSycl.hpp:18/home/fwyzard/src/alpaka-group/alpaka/include/alpaka/mem/buf/sycl/Accessor.hpp:
:27:/home/fwyzard/src/alpaka-group/alpaka/include/alpaka/mem/buf/sycl/Accessor.hpp48::27 :48: error: error: use of undeclared identifier 'experimental'; did you mean 'sycl::intel::experimental'?use of undeclared identifier 'experimental'; did you mean 'sycl::intel::experimental'?

        inline constexpr auto sycl_access_mode<experimental::ReadAccess> = sycl::access_mode::read;        inline constexpr auto sycl_access_mode<experimental::ReadAccess> = sycl::access_mode::read;

                                               ^~~~~~~~~~~~                                               ^~~~~~~~~~~~

                                               sycl::intel::experimental                                               sycl::intel::experimental
```

```
In file included from /home/fwyzard/src/alpaka-group/alpaka/include/alpaka/kernel/TaskKernelGenericSycl.hpp:18:
/home/fwyzard/src/alpaka-group/alpaka/include/alpaka/mem/buf/sycl/Accessor.hpp:27:48: error: no member named 'ReadAccess' in namespace 'sycl::ext::intel::experimental'; did you mean 'eaccess'?
        inline constexpr auto sycl_access_mode<experimental::ReadAccess> = sycl::access_mode::read;
                                               ^~~~~~~~~~~~~~~~~~~~~~~~
```

and so on

**Pull request merged**
