### PR TITLE
 Work around Intel ICE when using std::decay on empty template parameter packs

### LINKED ISSUE #995: std::decay_t causes internal compiler errors in Intel compiler
In TaskKernelCpuOmp2Blocks.hpp the lines 102 and 122 read

`[this](typename std::decay<TArgs>::type const & ... args)`

The std::decay in these lines produces an internal compiler in all Intel.2018 versions. 
In alpaka 0.3.5 these lines (there in ExecCpuOmp2Blocks.hpp) just read

`[this](TArgs const & ... args)`

Unfortunatly we can't switch to Intel.2019 or a newer version yet (since this causes other internal compiler errors in our code). However, if I just remove the std::decay in alpaka 0.4.1 I get a bunch of compilation errors. What is this std::decay for? If I want to remove it, what other changes do I need to make?

This is somehow related to #843

### PR DESCRIPTION
**Pull request by sbastrakov**
Fixes #995.

This is a simple workaround to get it fixed. My earlier PR #1067 attempted a more general change that gets rid of these `decay`s along the way. However, that one has its own issues, that will take time to resolve. So I will close that one for now.

To do:
- [x] merge #1070, this PR uses a commit from there.

Thanks to @krzikalla for communicating the way to fix.

### CODE REVIEW

**Review by psychocoderHPC — APPROVED** [review]

**Comment by sbastrakov** [comment]
Okay, so #1070 is now merged. And one of commits of this PR is the same as there. I assume it should be all fine right now, without rebasing?

**Comment by BenjaminW3** [comment]
Should be fine. I set `Rebase and merge` as default merge behaviour. This will cleanly get rid of the commit.

**Comment by psychocoderHPC** [comment]
Cc-ing: @jkelling This is important for SPEC

**Comment by sbastrakov** [comment]
Also perhaps the previously wrong Intel compiler identification, fixed in #1070, may be useful for @jkelling .

**Pull request merged**
