### PR TITLE
Add support for Visual Studio 2019

### PR DESCRIPTION
**Pull request by BenjaminW3**
This makes use of Github Actions for building on Windows with Visual Studio 2019.
We already use GitHub Actions for updating the doxygen documentation and it looks like the next reasonable step. Especially because it allows for 20 parallel builds for open source projects whereas Travis only has 5.

### CODE REVIEW

**Comment by BenjaminW3** [comment]
Ready for review/merge!

**Comment by BenjaminW3** [comment]
ready for review/merge ;-)

**Comment by psychocoderHPC** [comment]
Is this a replacement for travis tests? or an addition for the windows tests?

Only a note: we are working on getting the HZDR CI into alpaka to support scalable tests on multiple architectures (Linux, maybe MACOSX). Windows will stay on travis.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by BenjaminW3** [comment]
Currently this is both. VS 2019 tests are new but now directly within github. My goal is to move all the tests from travis to github. This would remove the necessity for yet another account.

**Pull request merged**
