### PR TITLE
Add support for clang-9.0.0

### PR DESCRIPTION
**Pull request by BenjaminW3**
We should support clang-9 for:
* non-CUDA builds
* clang as native CUDA compiler with CUDA 8.0-10.1

I currently see crashes of `ptxas` with older CUDA version. I added more build combinations to find the reason. Current assumption is that debug builds are the fault.
```
*** Error in `/usr/local/cuda-8.0/bin/ptxas': double free or corruption (!prev): 0x0000000001baad50 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fa58bb457e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fa58bb4e37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fa58bb5253c]
/usr/local/cuda-8.0/bin/ptxas[0x4b7daa]
/usr/local/cuda-8.0/bin/ptxas[0x4b7e4a]
/usr/local/cuda-8.0/bin/ptxas[0x4b80bb]
/usr/local/cuda-8.0/bin/ptxas[0x4ba6b5]
/usr/local/cuda-8.0/bin/ptxas(memspDelete+0x92)[0x4b7ef2]
/usr/local/cuda-8.0/bin/ptxas[0x42662f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fa58baee830]
/usr/local/cuda-8.0/bin/ptxas[0x420419]
======= Memory map: ========
00400000-00a01000 r-xp 00000000 08:01 4096761                            /usr/local/cuda-8.0/bin/ptxas
00c00000-00c3e000 rw-p 00600000 08:01 4096761                            /usr/local/cuda-8.0/bin/ptxas
00c3e000-00c57000 rw-p 00000000 00:00 0 
01117000-01e4a000 rw-p 00000000 00:00 0                                  [heap]
7fa584000000-7fa584021000 rw-p 00000000 00:00 0 
7fa584021000-7fa588000000 ---p 00000000 00:00 0 
7fa58b8b8000-7fa58b8ce000 r-xp 00000000 08:01 2062608                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa58b8ce000-7fa58bacd000 ---p 00016000 08:01 2062608                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa58bacd000-7fa58bace000 rw-p 00015000 08:01 2062608                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa58bace000-7fa58bc8e000 r-xp 00000000 08:01 2062587                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa58bc8e000-7fa58be8e000 ---p 001c0000 08:01 2062587                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa58be8e000-7fa58be92000 r--p 001c0000 08:01 2062587                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa58be92000-7fa58be94000 rw-p 001c4000 08:01 2062587                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa58be94000-7fa58be98000 rw-p 00000000 00:00 0 
7fa58be98000-7fa58bfa0000 r-xp 00000000 08:01 2062619                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa58bfa0000-7fa58c19f000 ---p 00108000 08:01 2062619                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa58c19f000-7fa58c1a0000 r--p 00107000 08:01 2062619                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa58c1a0000-7fa58c1a1000 rw-p 00108000 08:01 2062619                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa58c1a1000-7fa58c1b9000 r-xp 00000000 08:01 2062655                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa58c1b9000-7fa58c3b8000 ---p 00018000 08:01 2062655                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa58c3b8000-7fa58c3b9000 r--p 00017000 08:01 2062655                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa58c3b9000-7fa58c3ba000 rw-p 00018000 08:01 2062655                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa58c3ba000-7fa58c3be000 rw-p 00000000 00:00 0 
7fa58c3be000-7fa58c3e4000 r-xp 00000000 08:01 2062567                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa58c5d9000-7fa58c5dd000 rw-p 00000000 00:00 0 
7fa58c5e2000-7fa58c5e3000 rw-p 00000000 00:00 0 
7fa58c5e3000-7fa58c5e4000 r--p 00025000 08:01 2062567                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa58c5e4000-7fa58c5e5000 rw-p 00026000 08:01 2062567                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa58c5e5000-7fa58c5e6000 rw-p 00000000 00:00 0 
7ffc624e6000-7ffc62507000 rw-p 00000000 00:00 0                          [stack]
7ffc625d2000-7ffc625d5000 r--p 00000000 00:00 0                          [vvar]
7ffc625d5000-7ffc625d7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: ptxas command failed due to signal (use -v to see invocation)
clang version 9.0.0 (https://github.com/llvm-mirror/llvm c62b24f070c9a4bb1a76409e623042a740cac4cd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/travis/llvm/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/BlockSharedMemDyn-570ed9.cu
clang-9: note: diagnostic msg: /tmp/BlockSharedMemDyn-264d9a.cu
clang-9: note: diagnostic msg: /tmp/BlockSharedMemDyn-570ed9.sh
clang-9: note: diagnostic msg: 
********************
make[2]: *** [test/unit/block/shared/CMakeFiles/blockShared.dir/src/BlockSharedMemDyn.cpp.o] Error 254
```

We probably have to remove older CUDA verions from the supported versions of clang-9.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
I think it is no problem to remove CUDA-8 support if clang 9 is used. CUDA switched some things from CUDA 8 to 9, I assume this is the reason for the incompatibility.

**Comment by BenjaminW3** [comment]
We will probably have to exclude clang-9 native CUDA builds for CUDA 8.0, 9.0 and 9.1. CUDA-9.2 works.
The build results are not really consistent:
* clang-9 + CUDA-8.0 Release ✔️ 
* clang-9 + CUDA-8.0 Debug ❌ 
* clang-9 + CUDA-9.0 Release ❌  
* clang-9 + CUDA-9.0 Debug ❌ 
* clang-9 + CUDA-9.1 Release ✔️ 
* clang-9 + CUDA-9.1 Debug ❌

The failing builds all show the compiler crash.

**Comment by BenjaminW3** [comment]
I had to disable the Mac CI builds for now because they are failing consistently with a homebrew error message. We will have to investigate this separately.

**Comment by BenjaminW3** [comment]
~Ready for approvals ;-)~
Has to be rebased after #863 is merged

**Comment by BenjaminW3** [comment]
Rebased and ready for approval now!

**Comment by psychocoderHPC** [comment]
> I had to disable the Mac CI builds for now because they are failing consistently with a homebrew error message. We will have to investigate this separately.

I opened an issue to re-enable the tests that we do not forget about it #865

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
