### PR TITLE
Remove `ALPAKA_SYCL_BACKEND_ONEAPI`

### PR DESCRIPTION
**Pull request by j-stephan**
This PR removes the remaining occurrences of `ALPAKA_SYCL_BACKEND_ONEAPI` from the code base. I originally removed this preprocessor define as part of #1970 but forgot a few portions of the code. This would result in CMake-based builds not generating any SYCL accelerators for the test cases.

This is also a prerequisite for #2064.

### CODE REVIEW

**Review by bernhardmgruber — APPROVED** [review]

**Review by fwyzard — COMMENTED** [review]
Tested on the Intel Flex 170:
```
100% tests passed, 0 tests failed out of 42
```

Tested with the CPU back-end:
```
90% tests passed, 4 tests failed out of 42

The following tests FAILED:
         20 - atomicTest (Failed)
         21 - blockSharedTest (Failed)
         22 - blockSharedSharingTest (Failed)
         41 - warpTest (Failed)
```
(the failures are expected)

**Comment by j-stephan** [comment]
Interesting. Are you testing this with the current `develop`? The CPU back-end seems to work 100% in my CI PR.

**Comment by fwyzard** [comment]
> Are you testing this with the current `develop`?

Yes.

> The CPU back-end seems to work 100% in my CI PR.

I don't think I've seen these tests succeed on the CPU, yet.
What OpenCL runtime are you using ?

**Comment by j-stephan** [comment]
The one from the Intel apt-repository (`intel-oneapi-runtime-opencl`). But I just saw that my CI runners are not enabling the SYCL back-end for some reason :-(

**Pull request merged**
