### PR TITLE
add ROCm CI tests for version 5.6, 5.7

### LINKED ISSUE #1996: Support ROCm 5.6
https://rocm.docs.amd.com/en/docs-5.6.0/release.html

Our Radeon VII will be entering the maintenance mode starting with ROCm 5.7, which means it will not get new features. I think, it will still working.

### PR DESCRIPTION
**Pull request by SimeonEhrig**
fix #1996

- Update script to install HIP.
  - update environment variables
  - update installed packages
- update CMake max HIP version to 5.7
- fix wrong variable usage to find `rocrand`

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
The `install_hip.sh` script is broken.

**Comment by psychocoderHPC** [comment]
The problem is that `install_hip.sh` assumes that the rocm container will be used but the CI is using the alpaka base container.

**Comment by psychocoderHPC** [comment]
I pushed an update of the hip install script to support alpaka's base CI container

**Comment by SimeonEhrig** [comment]
@psychocoderHPC Maybe you can reduce the amount hip packages to install. See alpaka container: https://codebase.helmholtz.cloud/crp/alpaka-group-container/-/blob/master/generator/rocm.py?ref_type=heads#L75

**Comment by psychocoderHPC** [comment]
I updated the PR to test only ROCM 5.6 and 5.7

ROCm 6.0 will be a separate PR.

**Comment by SimeonEhrig** [comment]
The changes looks good but I cannot approve because I opened the PR :sweat_smile:

**Review by fwyzard — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
maybe @fwyzard will press the merge button.

**Comment by fwyzard** [comment]
I was waiting for the tests to complete :-)

**Pull request merged**
