### PR TITLE
add mdspan tests to the CI

### LINKED ISSUE #2049: CI is not running any tests with mdspan enabled
The CI is not runnign any tests that enable the use of `alpaka::experimental::mdspan`. The corresponding examples are not compiling at the moment because previous changes forgot to update those examples. We should add corresponding CI runs that include mdspan.

### PR DESCRIPTION
**Pull request by SimeonEhrig**

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
addresses issue #2049

**Comment by bernhardmgruber** [comment]
Your PR depends on #2051, which fixes a compilation error with mdspan.

**Comment by SimeonEhrig** [comment]
@bernhardmgruber Can you please have a look on the failed CI jobs. I found at least 2 different errors:

- https://gitlab.com/hzdr/crp/alpaka/-/jobs/4791261215
- https://gitlab.com/hzdr/crp/alpaka/-/jobs/4791261211

**Comment by bernhardmgruber** [comment]
I had a look and fixed the issues in #2053. There are compilation failures inside the mdspan headers with nvcc 11.2 though. I suggest we just remove that combination.

**Comment by SimeonEhrig** [comment]
@j-stephan I stopped the runtime pipeline to free resources for PR #2053 . As soon as the PR is merged I will rebase. Can you please review the single commit in the mean time. Maybe we can merge it before my vacations.

https://github.com/alpaka-group/alpaka/pull/2052/commits/a436a0d3305bbb98c497527797e44bf9473ea831

**Review by j-stephan — APPROVED** [review]

**Comment by j-stephan** [comment]
Note to self:

- [x] Merge #2053 first.

**Comment by bernhardmgruber** [comment]
@SimeonEhrig please rebase :)

**Comment by SimeonEhrig** [comment]
> @SimeonEhrig please rebase :)

Done. Let the CI become green ;-)

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
