### PR TITLE
Add Headers for standalone usage without CMake

### PR DESCRIPTION
**Pull request by BenjaminW3**
Implements standalone headers for #601

Please vote for your favorite:

Folder:
 * `backend`
 * ...

File names:
 * `BackendCpuThreads` (would be consistent with all other classes as they use the folder name as the prefix)
 * `EnableCpuThreads` (might be more natural language)
 * `CpuThreads` 

The defines themselves are already somehow inconsistemt as the include `ACC` but they do not only enable the compilation of an accelerator but a complete backend consisting of accelerator+kernel-execution-task+all other deps.

### CODE REVIEW

**Comment by bertwesarg** [comment]
To use alpaka without Cmake, one also has to `#define ALPAKA_DEBUG`. At least I can't find a `#ifndef ALPAKA_DEBUG/#define ALPAKA_DEBUG`.

**Comment by bertwesarg** [comment]
Would it make sense to put some basic error checking in these headers? I.e., the OpenMP backends could check for `_OPENMP`, plus versoin checks. `GpuCuda` could check `__CUDA__` or `__CUDACC__`. etc. p.p.

**Comment by BenjaminW3** [comment]
If `#define ALPAKA_DEBUG` is really necessary then this is a bug and I will try to fix this.

**Comment by BenjaminW3** [comment]
The checks for `_OPENMP` and the like are really useful and they are already part of alpaka. All the files relying on compiler support are guarded like this:

```c++
#ifdef ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED

#if _OPENMP < 200203
    #error If ALPAKA_ACC_CPU_B_SEQ_T_OMP2_ENABLED is set, the compiler has to support OpenMP 2.0 or higher!
#endif

...

#endif
```

So it is not necessary to duplicate this within those headers because the errors will be created either way.

**Comment by BenjaminW3** [comment]
@bertwesarg `core/Debug.hpp` contains
```
#ifndef ALPAKA_DEBUG
    //-----------------------------------------------------------------------------
    //! Set the minimum log level if it is not defined.
    #define ALPAKA_DEBUG ALPAKA_DEBUG_DISABLED
#endif
```

It should be included from all headers using `ALPAKA_DEBUG` because else the self-contained-header check together with the error for warning on usage of undeclared defines would lead to a build error.

**Comment by BenjaminW3** [comment]
You still can vote for the folder/file names (see top)!

**Comment by ax3l** [comment]
cc @SimeonEhrig : it's coming, this should help you with convenient cling-ing of Alpaka!

**Comment by ax3l** [comment]
I think `backend/` or `config/` are good folder names (we might need more helper headers besides backend selection, e.g. Debug, Verbosity, some kind of synchronization enforcement instead of streams, etc.).

I would say if it's in `backend/` then do not prefix the filename again `backend/CpuThreads.hpp`, otherwise in `config/BackendCpuThreads.hpp`.

We could also do `alpaka/enable/CpuThreads.hpp`, `alpaka/enable/Debug.hpp`, `alpaka/disable/CUDAstreams.hpp`, ... That's a bit like Apache configs and quite natural :D

**Comment by bertwesarg** [comment]
> @bertwesarg `core/Debug.hpp` contains
> 
> ```
> #ifndef ALPAKA_DEBUG
>     //-----------------------------------------------------------------------------
>     //! Set the minimum log level if it is not defined.
>     #define ALPAKA_DEBUG ALPAKA_DEBUG_DISABLED
> #endif
> ```
> 
> It should be included from all headers using `ALPAKA_DEBUG` because else the self-contained-header check together with the error for warning on usage of undeclared defines would lead to a build error.

Sorry, I missed that than.

**Comment by BenjaminW3** [comment]
We (@BenjaminW3 @bertwesarg @psychocoderHPC @sbastrakov @tdd11235813 @SimeonEhrig) voted offline for `standalone/CpuOmp2Threads.hpp`.

**Comment by BenjaminW3** [comment]
I would like to get this first step merged independently of future enhancements (e.g. boost version compatibility detection etc.).
Please approve!

**Comment by bertwesarg** [comment]
I'm fine with it.

**Review by sbastrakov — DISMISSED** [review]

**Comment by BenjaminW3** [comment]
Please approve!

**Comment by ax3l** [comment]
Okay with me :)

**Review by ax3l — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
There is a discussion in an [cupla issue](https://github.com/ComputationalRadiationPhysics/cupla/pull/112#issuecomment-499020489) That the naming `standalone` is maybe not good. @ComputationalRadiationPhysics/alpaka-maintainers please join the discussion. I like to have the same naming in alpaka and cupla to not confuse the user.
So we need to collect arguments for different namings to evaluate if we should rename `alpaka/standalone` or keep the naming.

**Comment by ax3l** [comment]
I think to avoid confusion with single-file, amalgated, dependency free "standalone header" projects [[1](https://github.com/mpark/variant/releases)] [[2](https://github.com/nlohmann/json)] [[3](https://github.com/catchorg/Catch2)] we should call those cmake-free headers "facade headers", which is the feature we are providing with them in common nomenclature [[4](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#which-pragma-should-i-use)].

**Pull request merged**
