### PR TITLE
CI: MSVC + nvcc workarounds and fixes

### PR DESCRIPTION
**Pull request by psychocoderHPC**
* Update CUDA download to the latest provided versions to fix CI issue:

  ```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30037\include\yvals_core.h(531): fatal 
  error C1189: #error:  STL1002: Unexpected compiler version, expected CUDA 10.1 Update 2 or newer
  ```
* include #1325 to fix MSVC + nvcc issues
* add workaround for #1331

### CODE REVIEW

**Review by bernhardmgruber — DISMISSED** [review]

**Review by j-stephan — DISMISSED** [review]

**Comment by j-stephan** [comment]
Looks like some of the CUDA download links are wrong, the setup reports a 404.

**Comment by psychocoderHPC** [comment]
Can someone see why this error happened? 

https://github.com/alpaka-group/alpaka/pull/1332/checks?check_run_id=2718746381#step:4:546

I tried to download CUDA on my gaming PC but and to check the command, unfortunately, the installer stops without any error message and `--help` is also not available :-(

**Comment by j-stephan** [comment]
> Can someone see why this error happened?

The link is broken. You can test it yourself with `wget` or `curl`:

```
wget http://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda_11.2.2_461.33_win10.exe
--2021-06-02 09:23:29--  http://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda_11.2.2_461.33_win10.exe
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 152.199.20.126
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|152.199.20.126|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-06-02 09:23:30 ERROR 404: Not Found.
```

**Comment by psychocoderHPC** [comment]
> Can someone see why this error happened?
> 
> https://github.com/alpaka-group/alpaka/pull/1332/checks?check_run_id=2718746381#step:4:546
> 
> I tried to download CUDA on my gaming PC but and to check the command, unfortunately, the installer stops without any error message and `--help` is also not available :-(

I found the issue the URL has changed. it is now `https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/...`

**Comment by SimeonEhrig** [comment]
> Can someone see why this error happened?
> 
> https://github.com/alpaka-group/alpaka/pull/1332/checks?check_run_id=2718746381#step:4:546
> 
> I tried to download CUDA on my gaming PC but and to check the command, unfortunately, the installer stops without any error message and `--help` is also not available :-(

@BenjaminW3 showed me on an alpaka hackathon that the Windows installer of cuda does not give an error message when an error occurs. One solution was to check if executables, libraries and so on are present in the installation folder.

**Review by bernhardmgruber — APPROVED** [review]

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
I pushed an update to test windows only and will add the C++17 fix as soon as I know which windows runs are failing.

**Comment by psychocoderHPC** [comment]
For testing I pulled now also #1325 into this PR because the CI was failing in the OMP scheduler tests :-(

**Comment by j-stephan** [comment]
Looks like NVIDIA's workaround doesn't fix the Visual Studio incompatibility for CUDA 11.0 and 11.1 :-( But at least 11.2 and 11.3 seem to work again.

**Comment by psychocoderHPC** [comment]
> Looks like NVIDIA's workaround doesn't fix the Visual Studio incompatibility for CUDA 11.0 and 11.1 :-( But at least 11.2 and 11.3 seem to work again.

It looks like CUDA 11.0 and 11.1 are new issues: https://github.com/alpaka-group/alpaka/pull/1332/checks?check_run_id=2728484541#step:4:2903

The new error sounds like issues with `std::invoke_result` https://en.cppreference.com/w/cpp/types/result_of
Let us check maybe we use this wrongly. `invoke_result` must be well-formed else the behavior is undefined.
So we are not allowed to use it in the query the result of we not checked before that the functor we check is invokable.

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
