### PR TITLE
Move CI builds completely from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by BenjaminW3**
Refactorings of the build scripts will be done independently later.

Advantages:
* branch build time reduced from 4:30h to 2:10h
* only one account required - no need to switch platforms to view builds
* possibility to selectively require build jobs as merge barrier

Disadvantages:
* as of yet github Actions do not provide the possibility to rebuild a single job but only all at once

### CODE REVIEW

**Comment by BenjaminW3** [comment]
This is based on #1007. We can either merge it in order or close #1007.

**Comment by psychocoderHPC** [comment]
> This is based on #1007. We can either merge it in order or close #1007.

Do not close #1007 it will be automatically closed when this PR is merged. For referencing possible issues it is better to have those changes in different PR's.

**Comment by BenjaminW3** [comment]
Please review this PR. Once this is merged, I will disable the Travis CI build trigger.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
we need activate in setting of this repository that all actions must pass before we are allowed to merge.

**Comment by BenjaminW3** [comment]
I am doing this just now ;-)

**Pull request merged**
