### PR TITLE
Fix undefined constant with nvcc 12.0

### LINKED ISSUE #1877: Compile error with nvcc 12 and gcc 12
When I compile the unit tests with nvcc 12 and gcc 12 I get the following error:

```
/home/bgruber/dev/alpaka/include/alpaka/test/event/EventHostManualTrigger.hpp(383): error: identifier "CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS" is undefined

1 error detected in the compilation of "/home/bgruber/dev/alpaka/test/unit/event/src/EventTest.cpp".
```
Maybe this constant has been removed or moved to a different header?

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #1877

### CODE REVIEW

**Review by j-stephan — COMMENTED** [review]
Is there no replacement for the deprecated enum value? I would rather see this modernized instead of failing in the future.

**Comment by bernhardmgruber** [comment]
I don't know what the replacement is and I neither have the time nor expertise to look into this. But the issue is blocking me, so here is a fix that at least allows compilation to succeed again with nvcc 12.0.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
I will merge this PR to avoid blocking others. It is normal that NVIDIA is removing defines. 
This is a driver API definition that is only used for testing. In general, we should maybe replace the usage in the test by using system atomics, if I remember correctly we use this flag for the queue or event test only to block a task and release it in a well-defined order.

**Comment by psychocoderHPC** [comment]
I opened an issue that we should check if the usage of this driver API define can be replaced: https://github.com/alpaka-group/alpaka/issues/1881

**Pull request merged**
