### PR TITLE
HIP: remove copy device2device workaround

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- fix compile issue with HIP 3.9
  - due to interface change
`hipBlockIdx_x,...` is now 64bit and requires a statci cast to create a
vector
  - since the performance issue for d2d copies are solved in HIP the
workaround can be removed
- remove d2d memcopy workaround
  - remove cmake option `ALPAKA_EMU_MEMCPY3D`
  - remove memcopy kernel with workaround

This PR should go into 0.6.0

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
~~`ALPAKA_EMU_MEMCPY3D` must be removed from the docs~~

**Comment by SimeonEhrig** [comment]
> `ALPAKA_EMU_MEMCPY3D` must be removed from the docs

You simply need to remove lines 223-226 in `docs/source/advanced/cmake.rst`.

**Comment by sbastrakov** [comment]
I think this should also be removed from ci.yaml.

**Comment by psychocoderHPC** [comment]
> I think this should also be removed from ci.yaml.

I removed the left over usage for the CI

**Comment by SimeonEhrig** [comment]
Is HIP 3.9 the minimum requirement? If yes, please update the `readme.md`.

**Comment by psychocoderHPC** [comment]
> Is HIP 3.9 the minimum requirement? If yes, please update the `readme.md`.

no still HIP 3.5.

**Review by BenjaminW3 — APPROVED** [review]

**Review by sbastrakov — APPROVED** [review]

**Comment by sbastrakov** [comment]
CI failed for unrelated reason. I will merge it.

**Pull request merged**
