### PR TITLE
Strip namespaces from mathTest

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Just ran into the deeply nested namespaces inside the `mathTest` and decided to remove them to save indentation.

### CODE REVIEW

**Comment by bernhardmgruber** [comment]
Make sure you hide whitespace changes when reviewing!

**Comment by fwyzard** [comment]
What about the other `alpaka::test` namespace usage ?

**Comment by bernhardmgruber** [comment]
> What about the other `alpaka::test` namespace usage ?

My PR just concerns the `mathTest` internals. I think `alpaka::test` is used more widespread. Especially also in public headers of the alpaka library itself.

**Comment by psychocoderHPC** [comment]
Is it really a good idea to move all code in the hpp-files into the global namespace? There is a small possibility of naming conflicts.
I tend to have my own code always encapsulated within a namespace.

**Comment by bernhardmgruber** [comment]
> Is it really a good idea to move all code in the hpp-files into the global namespace? There is a small possibility of naming conflicts. I tend to have my own code always encapsulated within a namespace.

My thought process was to reduce all the nesting to a nested namespace specifier. Then I figured it is still too long when prefixing entities from the nested namespace. I looked into other unit tests where I saw no namespaces being used. Then I decided to remove them.

I honestly don't care whether we have no namespace or a small one for local header files in unit tests. From the best practices, maybe having a namespace is better than declaring in the global namespace. I can add one then.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
