### PR TITLE
Use newer boost (1.67+) for clang-7 & c++17 & libstdc++

### PR DESCRIPTION
**Pull request by BenjaminW3**
This combination was disabled when the C++17 support was added. A newer boost version resolves the issue.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Ok but should we document this somewhere and check the versions match in our CMake file?
Because Alpaka still supports Boost 1.62.0+.

**Comment by BenjaminW3** [comment]
I have not yet found a way to check the standard library and the version that is used in CMake because this is completely a decision of the user via additional compile flags.

**Comment by ax3l** [comment]
Ah ok, then maybe let us at least document the requirement on dependencies in `README.md`?

**Comment by BenjaminW3** [comment]
I will add it to the readme.

**Pull request merged**
