### PR TITLE
Remove ALPAKA_FN_HOST_ACC on defaulted functions

### LINKED ISSUE #1760: Warnings in Complex
We recently upgraded alpaka in the [LCG distribution](https://lcgdocs.web.cern.ch/lcgdocs/lcgreleases/introduction/) and now we get the following warnings:
```
/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Tue/x86_64-centos8-gcc11-opt/include/alpaka/math/Complex.hpp(56): warning #20012-D: __device__ annotation is ignored on a function("Complex") that is explicitly defaulted on its first declaration

/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Tue/x86_64-centos8-gcc11-opt/include/alpaka/math/Complex.hpp(56): warning #20012-D: __host__ annotation is ignored on a function("Complex") that is explicitly defaulted on its first declaration

/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Tue/x86_64-centos8-gcc11-opt/include/alpaka/math/Complex.hpp(78): warning #20012-D: __device__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration

/cvmfs/sft-nightlies.cern.ch/lcg/views/dev4/Tue/x86_64-centos8-gcc11-opt/include/alpaka/math/Complex.hpp(78): warning #20012-D: __host__ annotation is ignored on a function("operator=") that is explicitly defaulted on its first declaration
```
The warnings can be fixed be removing `ALPAKA_FN_HOST_ACC` from the affected declarations.

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #1760

### CODE REVIEW

**Review by j-stephan — APPROVED** [review]

**Review by sbastrakov — COMMENTED** [review]
I am not sure how is that a fix - those functions must be host-device.
Or is it that compilers for CUDA/HIP will use host-device automatically for `= default` methods?

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
> I am not sure how is that a fix - those functions must be host-device. Or is it that compilers for CUDA/HIP will use host-device automatically for `= default` methods?

Yes the compiler will add it. CUDA is throwing this warning now since 2 years or more.

**Comment by psychocoderHPC** [comment]
Mhh maybe the nvcc flag where you can use host constexpr functions within the device code making the difference.
@sbastrakov said offline that maybe the attribute `ALPAKA_FN_HOST_ACC` is required for `constexpr` constructors.

**Comment by sbastrakov** [comment]
Yes, well I am not sure what are exact requirements. I think since this PR passed through our CI, and also solves the issue on another system, it is fine.

**Comment by bernhardmgruber** [comment]
> Mhh maybe the nvcc flag where you can use host constexpr functions within the device code making the difference.
@sbastrakov said offline that maybe the attribute ALPAKA_FN_HOST_ACC is required for constexpr constructors.

No, it is irrelevant whether a defaulted special member is`constexpr` or not. nvcc just warns when you mark defaulted special members with `__host__` or `__device__`. See e.g. the assignment operator in this changeset:
```c++
 Complex& operator=(Complex const&) = default;
 ```

**Pull request merged**
