### PR TITLE
[clang-format] Apply clang-format

### PR DESCRIPTION
**Pull request by j-stephan**
This PR applies the new CRP clang-format ruleset to alpaka.

### CODE REVIEW

**Comment by j-stephan** [comment]
Interesting, all of a sudden the compilers choke on namespaces.

Before:

```c++
namespace alpaka
{
    namespace detail
    {
        template<
            std::size_t Tidx>
        struct CreateReverse
        {
            ALPAKA_NO_HOST_ACC_WARNING
            template<
                typename TDim,
                typename TVal>
            ALPAKA_FN_HOST_ACC static auto create(
                Vec<TDim, TVal> const & vec)
            -> TVal
            {
                return vec[TDim::value - 1u - Tidx];
            }
        };
    }

    namespace traits
    {
        template<
            typename TDim,
            typename TVal>
        struct ReverseVec<
            Vec<TDim, TVal>>
        {
            ALPAKA_NO_HOST_ACC_WARNING
            ALPAKA_FN_HOST_ACC static auto reverseVec(
                Vec<TDim, TVal> const & vec)
            -> Vec<TDim, TVal>
            {
                return
                    createVecFromIndexedFn<
                        TDim,
                        detail::CreateReverse>(
                            vec);
            }
        };
    }
}
```

After:

```c++
namespace alpaka
{
    namespace detail
    {
        template<std::size_t Tidx>
        struct CreateReverse
        {
            ALPAKA_NO_HOST_ACC_WARNING
            template<typename TDim, typename TVal>
            ALPAKA_FN_HOST_ACC static auto create(Vec<TDim, TVal> const& vec) -> TVal
            {
                return vec[TDim::value - 1u - Tidx];
            }
        };
    }

    namespace traits
    {
        template<typename TDim, typename TVal>
        struct ReverseVec<Vec<TDim, TVal>>
        {
            ALPAKA_NO_HOST_ACC_WARNING
            ALPAKA_FN_HOST_ACC static auto reverseVec(Vec<TDim, TVal> const& vec) -> Vec<TDim, TVal>
            {
                return createVecFromIndexedFn<TDim, detail::CreateReverse>(vec);
            }
        };
    }
}
```

Error:

```
home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp: In static member function 'static alpaka::Vec<TDim, TVal> alpaka::traits::ReverseVec<alpaka::Vec<TDim, TVal> >::reverseVec(const alpaka::Vec<TDim, TVal>&)':
/home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp:574:61: error: 'CreateReverse' is not a member of 'alpaka::traits::detail'; did you mean 'alpaka::detail::CreateReverse'?
  574 |                 return createVecFromIndexedFn<TDim, detail::CreateReverse>(vec);
      |                                                             ^~~~~~~~~~~~~
/home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp:553:16: note: 'alpaka::detail::CreateReverse' declared here
  553 |         struct CreateReverse
      |                ^~~~~~~~~~~~~
```

This seems to be consistent across compilers. @bernhardmgruber Any ideas why this is happening now and not when you removed the previous namespaces?

**Comment by bernhardmgruber** [comment]
My gut feeling is that the error is caused by a change in the include order of the headers. Therefore the context is different when the compiler parses `detail::CreateReverse`. My guess is that at the moment of name lookup a namespace `alpaka::traits::detail` now exists, that did not exist before. Therefore the compiler will search for `CreateReverse` there and fail. If such a namespace did not exist before, than the compiler would fallback to searching the namespace `alpaka::detail` where it successfully finds the declaration.

My advice: try to apply clang-format without reordering the includes for now. Then we do another PR with the includes reordered and a lot of additional namespace qualifiers, at least where required to compile.

**Comment by sbastrakov** [comment]
I think @bernhardmgruber 's suggestion is likely correct. I've recently encountered a similarly looking error when working on another thing, and it turned out to be that case. This code of using `detail::` is not correct (but probably rather frequently used), as it relies on the fact there is no internal namespace `detail::` inside namespace `traits`. Instead, it should either use full `alpaka::detail::...` or have `using namespace ...` before.

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by bernhardmgruber** [comment]
So, while I would gladly see this PR merged, it also introduces severe conflicts for all existing branches other than develop. Should we wait for some of the other PRs to be merged in? Notably #1127 .

If not, rebasing afterwards is full of conflicts, which can be solved automatically, by accepting all changes from HEAD and applying a clang-format before each `git rebase --continue`. But it takes a while and feels messy.

**Comment by psychocoderHPC** [comment]
please add the clangformat file in a seperate commit within this PR.

**Comment by psychocoderHPC** [comment]
Which commamd do you executed to format the full codebase?

**Comment by psychocoderHPC** [comment]
@alpaka-group/alpaka-maintainers please wait with mergin rhere are comming bugfixes today for the release candidate if this formating is merged before everything we be more complicate.

**Comment by j-stephan** [comment]
> please add the clangformat file in a seperate commit within this PR.

Will do once we have sorted out the header include order.

> Which commamd do you executed to format the full codebase?

Three commands actually:

```bash
find example -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
find include -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
find test -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
```

Executed from the top-level alpaka directory with `.clang-format` in the same directory.

**Comment by j-stephan** [comment]
> Three commands actually:

Now that I think about it these can be merged into one command:

```bash
find example include test -name '*.hpp' -o -name '*.cpp' | xargs clang-format -i --style=file
```

**Comment by psychocoderHPC** [comment]
We should add the format file as the last change on top of the release candidate for 0.6.0 to simplify backports in the next month.

**Comment by j-stephan** [comment]
> Will do once we have sorted out the header include order.

To make this clearer: I will get on that tomorrow.

**Comment by psychocoderHPC** [comment]
> So, while I would gladly see this PR merged, it also introduces severe conflicts for all existing branches other than develop. Should we wait for some of the other PRs to be merged in? Notably #1127 .
> 
> If not, rebasing afterwards is full of conflicts, which can be solved automatically, by accepting all changes from HEAD and applying a clang-format before each `git rebase --continue`. But it takes a while and feels messy.

I am would suggest waiting for OpenACC but then @jkelling must give us a time when he thinks that the PR is ready. Currently, OpenACC is marked as WIP.

**Comment by jkelling** [comment]
Currently waiting for the CI to go through. The current state has an experiment suggested by @bernhardmgruber [here](https://github.com/alpaka-group/alpaka/pull/1127#discussion_r518622156_). Some test(s) may fail because of a warning, in which case I need to revert this and push again.

Otherwise it is ready from my side, if there are no one opts for changing things on [this question about `CtxBlockOacc`](https://github.com/alpaka-group/alpaka/pull/1127#issuecomment-724021729_).

**Comment by bernhardmgruber** [comment]
@jkelling there are several comments I made that have not yet been addressed. Maybe you have overlooked them. I marked you in the ones where I either expect changes from you or a short explanation why we should leave it. Please have another look! Thx!

**Comment by jkelling** [comment]
Thanks for pinging. These were not displayed to me by Github. But now, for most the only comment is "`@jkelling`", but I guess it will be clear what your mean.

**Comment by bernhardmgruber** [comment]
Yes, it's weird, because I commented on my previous comments, but they are shown independenly now :/ Try to expand the discussion on Github, you will find them!

**Comment by bernhardmgruber** [comment]
@j-stephan I think you can rebase this PR now and also format all the new files that came in with #1127

**Comment by j-stephan** [comment]
Okay, after the CI is through this _should_ be ready to merge.

**Review by bernhardmgruber — APPROVED** [review]

**Comment by j-stephan** [comment]
Looks good, CI works except for the broken macOS instances.

**Review by BenjaminW3 — APPROVED** [review]

**Pull request merged**
