### PR TITLE
Docs: GTC 2016 Persistent Archive

### LINKED ISSUE #856: Link to GTC 2016 Talk in Readme.md broken
The first Link for introduction material Introduction is broken:
"For a quick introduction, feel free to playback the recording of our presentation at GTC 2016:" links to http://mygtc.gputechconf.com/quicklink/858sI36 which requires a login.
I recommend just uploading the slides in ROBIS and linking to them there.

### PR DESCRIPTION
**Pull request by ax3l**
I created a persistent archive of our GTC 2016 presentation, so that it does not get lost should the homepage go offline at some point.

### CODE REVIEW

**Comment by bussmann** [comment]
Should there be a general subdirectory for presentations ob openPMD?

**Comment by ax3l** [comment]
This is our GTC '16 Alpaka talk.

Definitely, people should add a hashtag alpaka or openPMD, respectively when uploading talks to rodare/zenodo. I definitely do that :)

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by j-stephan** [comment]
Please rebase! The CI issues have been fixed.

**Comment by j-stephan** [comment]
@ax3l

**Comment by psychocoderHPC** [comment]
> Please rebase! The CI issues have been fixed.

I rebased the PR, thx @ax3l for providing the persistent link.

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
