### PR TITLE
Isolate parallel region for nested parallelism with tbb backend

### LINKED ISSUE #1449: Inner-loop parallelism is not isolated when using tbb backend
When using alpaka tbb backend from within a parallel section of a code that is already parallelized using tbb, the alpaka kernel  becomes the innermost parallel loop of a nested parallel section.
As tbb treats all the tasks the same, whether they come from the outermost or the innermost loop and a thread might steal a task. If not protected, this might lead to deadlocks or unexpected results.

More details in: 
https://link.springer.com/chapter/10.1007/978-1-4842-4398-5_12

### PR DESCRIPTION
**Pull request by felicepantaleo**
This PR solves the issue https://github.com/alpaka-group/alpaka/issues/1449

Some benchmarks will follow.

### CODE REVIEW

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
@felicepantaleo Thanks for your first alpaka pull-request.

**Review by sbastrakov — DISMISSED** [review]
Why didn't you add yourself to the copyright note?

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by bernhardmgruber** [comment]
This PR seems to fail compilation because of missing TBB features. I am assuming you have a fairly modern version of TBB (i.e. oneTBB)? I created a PR to update to oneTBB here: #1456.

**Comment by fwyzard** [comment]
While in our production environment (CMSSW) we are indeed using v2021.4, in the `pixeltrack-standalone` test bench we are still using TBB v2020.3, _i.e._ the last tag before the breaking changes introduced in oneTBB.

Moving to oneTBB v2021.x is on the todo list...

**Comment by bernhardmgruber** [comment]
> Moving to oneTBB v2021.x is on the todo list...

I ran into troubles with oneTBB 2021.1 in #1456 so I use 2021.2. Would that work for you or do you require support for an older version of oneTBB? Could we even use a newer version of oneTBB as minimum?

**Comment by fwyzard** [comment]
If you switch to oneTBB 2021, I would suggest the latest one, currently v2021.4

**Comment by bernhardmgruber** [comment]
We switched to oneTBB 2021.4 now: #1456. Please rebase your PR.

**Review by bernhardmgruber — APPROVED** [review]

**Review by psychocoderHPC — APPROVED** [review]

**Comment by bernhardmgruber** [comment]
> Some benchmarks will follow.

@felicepantaleo I trust you that your changeset improves the TBB backend, since I cannot verify this easily. If you ever do another benchmark, please post it. I would be curious!

**Comment by psychocoderHPC** [comment]
@felicepantaleo thanks for the PR, @bernhardmgruber thanks for updating the CI to support TBB versions which allow using the task arena feature.

**Pull request merged**
