### PR TITLE
[Do not merge] Test timeout in queueTest on develop

### PR DESCRIPTION
**Pull request by jkelling**

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@jkelling Do you have any news related to this bug?

**Comment by jkelling** [comment]
> @jkelling Do you have any news related to this bug?

No, I did not look into this further.

**Comment by bernhardmgruber** [comment]
Ping! The queue test bug occurs a lot recently. There has not been a single CI run that completed without manual intervention for me. Any news on fixing this?

**Comment by bernhardmgruber** [comment]
@jkelling could you please retest whether there is still a timeout somewhere in the tests? And if there is not, please close the PR! Thx!

**Comment by bernhardmgruber** [comment]
@jkelling since we think we squashed the queue bug now with #2026, can you please reevaluate whether you still need this PR? And if not, please close it. Thx!

**Comment by j-stephan** [comment]
Hi @jkelling, is this PR still needed? The issue might have been closed by #2026.

**Comment by bernhardmgruber** [comment]
@jkelling ping.

**Comment by jkelling** [comment]
Related issue closed by https://github.com/alpaka-group/alpaka/pull/1870

**Pull request closed without merging**
