### PR TITLE
update github links to alpaka and cupla

### PR DESCRIPTION
**Pull request by psychocoderHPC**
Set links to the nex alpaka location.

### CODE REVIEW

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
@BenjaminW3  do you know why `continuous-integration/travis-ci ` is in the test list and not provide the Details button?

**Comment by BenjaminW3** [comment]
I do not know where this is coming from. It looks like it is the old Travis integration point that was replaced by the new version some time ago.

**Comment by psychocoderHPC** [comment]
Could be my fault I installed the travis app to the organisation. I removed it now

**Comment by BenjaminW3** [comment]
I would prefer the travis app over the old thing. At the old place I think we had a link to the travis results and it looked like the app.

**Comment by psychocoderHPC** [comment]
Yes, reactivated the travis app again. I have not configured the old way but could be I need to remove the webhook fully.

**Comment by BenjaminW3** [comment]
Maybe it automatically re-enabled itself when the Repo was moved.

**Comment by psychocoderHPC** [comment]
OK I need remove the check for the branch

**Comment by psychocoderHPC** [comment]
gitissue

Somehow I miss the option `Travis CI - Pull Request` to say that this test must pass befor ethe PR can be merged. I have it in cupla but somehow not in alpaka.

**Comment by psychocoderHPC** [comment]
OK I pushed this PR again and now it was also able to activate this option

**Comment by psychocoderHPC** [comment]
note: I activated also all other CI test as required too.

**Comment by psychocoderHPC** [comment]
@BenjaminW3 Do you ever restarted the actions because one of the tests failed?
I realized that it is only possible to restart all actions, not only the broken pipe. After restarting all tests will fail (see current output). Maybe you know better whats going wrong after restarting the tests.

I saw this error in the past also before we transferred the repo, so this will not be the root of the issue.

**Comment by BenjaminW3** [comment]
Restarting individual jobs is not possible yet. Restarting all always failed for me. That was the reason why I did not require the github builds yet.

**Review by BenjaminW3 — APPROVED** [review]

**Comment by BenjaminW3** [comment]
I disabled the github actions build as merge barrier for now. Maybe our build scripts are doing something wrong that makes the rebuilds fail.

**Comment by psychocoderHPC** [comment]
> Restarting individual jobs is not possible yet. Restarting all always failed for me. That was the reason why I did not require the github builds yet.

Ahh ok, than we should remove the require for now.

**Pull request merged**
