### PR TITLE
CI: test ROCm 5.5

### LINKED ISSUE #1948: Support ROCm 5.5
https://github.com/RadeonOpenCompute/ROCm/releases/tag/rocm-5.5.0

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #1948

Add ROCm 5.5 to the CI.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@SimeonEhrig 

Could you please help why the following error shows after adding HIPCC 5.5

```
RuntimeError: generate_job_yaml.job_variables(): unknown hip version: 5.5
```

**Comment by psychocoderHPC** [comment]
> @SimeonEhrig
> 
> Could you please help why the following error shows after adding HIPCC 5.5
> 
> ```
> RuntimeError: generate_job_yaml.job_variables(): unknown hip version: 5.5
> ```

OK I need to adjust for ROCM (HIPCC) `generator_job_yaml.py` too to know the clang version too.

**Review by j-stephan — CHANGES_REQUESTED** [review]
Looks good, but `README.md` needs to be updated, too.

**Comment by psychocoderHPC** [comment]
> Looks good, but `README.md` needs to be updated, too.

I updated the documentation in README.md too.

**Review by j-stephan — DISMISSED** [review]

**Review by j-stephan — APPROVED** [review]

**Review by SimeonEhrig — APPROVED** [review]

**Review by bernhardmgruber — APPROVED** [review]

**Pull request merged**
