### PR TITLE
Add RNG support for the SYCL back-end

### LINKED ISSUE #1605: Add random number support to SYCL back-end
The SYCL back-end currently does not allow for device-side RNGs. We should investigate whether the Philox implementation can be utilized here.

### PR DESCRIPTION
**Pull request by j-stephan**
I checked out the RNG-related changes files from #1845 and put them into an own commit.

Please merge #1982 first. Fixes #1605.

Thanks to @AuroraPerego, @Parsifal-2045 and @fwyzard for their good work.

@Parsifal-2045 Your e-mail address in the original commit(s) is not your CERN e-mail. Should it stay this way or do you want me to change it to the CERN e-mail for the RNG commit?

### CODE REVIEW

**Comment by Parsifal-2045** [comment]
> @Parsifal-2045 Your e-mail address in the original commit(s) is not your CERN e-mail. Should it stay this way or do you want me to change it to the CERN e-mail for the RNG commit?

Yes, thank you

**Comment by fwyzard** [comment]
Force-pushed to fix the conflicts and make GitHub happy, [no actual changes](https://github.com/alpaka-group/alpaka/compare/b1ca9264b647def5f6bd16a76d206e2499429182..c288e57f161954001660cc878e46aa50ae06f699).

**Comment by fwyzard** [comment]
Please merge #1985 and #1982 first.

**Comment by fwyzard** [comment]
It turns out that rebasing #1845 on top of this PR is significantly more complicated.
I would propose to delay or close this PR until the work in #1845 is completed, and can be factored out more easily.

**Comment by j-stephan** [comment]
@fywzard We can close this one since it has been merged as part of #1845, right?

**Comment by fwyzard** [comment]
I think so.

**Pull request closed without merging**
