### PR TITLE
Remove the dependency on Intel MKL

### PR DESCRIPTION
**Pull request by fwyzard**

### CODE REVIEW

**Review by j-stephan — DISMISSED** [review]
Looks good to me. Since we don't have a CI yet I assume the tests are successfully compiled on your machine?

**Comment by fwyzard** [comment]
I think so... let me give it another try :-)

**Review by j-stephan — APPROVED** [review]

**Comment by fwyzard** [comment]
Let's delay this, I got a crash while testing that _should_ be unrelated... but I'll need to check.

**Comment by fwyzard** [comment]
Looks like my setup is broken, independently from this PR.
@AuroraPerego confirmed that the change works :-)

**Pull request merged**
