### PR TITLE
[clang-format] Header ordering

### PR DESCRIPTION
**Pull request by j-stephan**
**Do not merge this right away: apply #1194 first!**

This PR reorders the includes in `example`, `include` and `test`. This was done automatically by using clang-format (same command as in #1194). I defined the following rules for the include groups:

0. All groups are ordered alphabetically.
1. If present, include the corresponding local header file for a `*.cpp` file. So if we are looking at `something.cpp`, first do
```c++
#include "something.hpp"
```
2. All other local header files form the next group: 
```c++
#include "somethingDifferent.hpp"
#include "somethingElse.hpp"
```
3. Include the alpaka header(s) next:
```c++
#include <alpaka/alpaka.hpp>
```
4. Then any third-party libraries:
```c++
#include <thirdParty/somethingSpecial.hpp>
```
5. Then catch2:
```c++
#include <catch2/catch2.hpp>
```
6. Then boost:
```c++
#include <boost/somethingBoosty.hpp>
```
7. Standard library last:
```c++
#include <string>
#include <vector>
```

Full example:
```c++
// In something.cpp:
#include "something.hpp"

#include "somethingDifferent.hpp"
#include "somethingElse.hpp"

#include <alpaka/alpaka.hpp>

#include <thirdParty/somethingSpecial.hpp>

#include <catch2/catch2.hpp>

#include <boost/somethingBoosty.hpp>

#include <string>
#include <vector>
```

I needed to manually fix two issues:

1. Use a full `alpaka::` namespace in `vec/Vec.hpp`.
2. `test/common/include/alpaka/test/Extent.hpp` required `<cstddef>` and `<alpaka/alpaka.hpp`. I noticed that the header files in our test directory don't seem to be self-contained. We should address this in a separate PR.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
Do you change the clang-format file to introduce the groups? If so please make the change in the clang-format file in a seperate commit visible.
Or do we have groups already enabled in the clang file?

**Comment by j-stephan** [comment]
Those are the project-specific options in the CRP `.clang-format` (commented out by default). I will submit a separate PR with the `.clang-format` used for this PR and #1194.

**Comment by psychocoderHPC** [comment]
> Those are the project-specific options in the CRP `.clang-format` (commented out by default). I will submit a separate PR with the `.clang-format` used for this PR an #1194.

It is also enough to have as seperate commit. The only requirement is that it is possible to have a diff. Together with all other formatations, it is not possible. IMO no need for a seperate PR.

**Comment by j-stephan** [comment]
Looks like something is wrong with the macOS CI:

```
xcode-select: error: invalid developer directory '/Applications/Xcode_11.app/Contents/Developer'
```

**Comment by psychocoderHPC** [comment]
> Looks like something is wrong with the macOS CI:
> 
> ```
> xcode-select: error: invalid developer directory '/Applications/Xcode_11.app/Contents/Developer'
> ```

I am currently fixing the issue. Xcode 11.1 is no longer avaiable

**Comment by bernhardmgruber** [comment]
Why do we need to split headers into 7 groups? That seems too excessive to me. We could at least leave 3rd party headers together. I also do not see the point of separating out the alpaka headers. Since the groups are sorted lexicographically, all alpaka, boost etc. headers will form a sequence anyway:

```
// In something.cpp:
#include "something.hpp"

#include "somethingDifferent.hpp"
#include "somethingElse.hpp"

#include <alpaka/alpaka.hpp>
#include <alpaka/alpaka/...>
#include <boost/somethingBoosty.hpp>
#include <boost/somethingElseBoosty.hpp>
#include <catch2/catch2.hpp>
#include <thirdParty/somethingSpecial.hpp>

#include <string>
#include <vector>
```

I think we could save some whitespace this way.

**Comment by BenjaminW3** [comment]
For me, separating the library internal headers from 3rd-party headers is still useful to improve readability. For alpaka it might be ok because it starts with a but for other libraries they would be somewhere in between.
So my proposal:
```
// In something.cpp:
#include "something.hpp"

#include "somethingDifferent.hpp"
#include "somethingElse.hpp"

#include <alpaka/alpaka.hpp>
#include <alpaka/alpaka/...>

#include <boost/somethingBoosty.hpp>
#include <boost/somethingElseBoosty.hpp>
#include <catch2/catch2.hpp>
#include <thirdParty/somethingSpecial.hpp>

#include <string>
#include <vector>
```

**Comment by BenjaminW3** [comment]
Note: in alpaka we nearly nowhere have the
```
#include "somethingDifferent.hpp"
#include "somethingElse.hpp"
```
block.

**Comment by j-stephan** [comment]
I like @BenjaminW3's proposal. Admittedly having boost and catch2 as separate categories was a bit shaky and - due to their limited usage - not that useful. Is everyone else okay with that?

Example:

```c++
// In something.cpp:
#include "something.hpp"

#include "somethingDifferent.hpp"
#include "somethingElse.hpp"

#include <alpaka/alpaka.hpp>

#include <boost/somethingBoosty.hpp>
#include <catch2/catch2.hpp>
#include <thirdParty/somethingSpecial.hpp>

#include <string>
#include <vector>
```

@bernhardmgruber @psychocoderHPC @SimeonEhrig @sbastrakov @jkelling

**Comment by jkelling** [comment]
I prefer having boost separate below other third-party libs (which may or may not be split into one block per lib) and above STL(/stdlib). But I am ok with this grouping, too.

**Review by bernhardmgruber — DISMISSED** [review]

**Comment by bernhardmgruber** [comment]
@j-stephan please rebase!

**Comment by BenjaminW3** [comment]
Build is broken:
```
In file included from /home/runner/work/alpaka/alpaka/include/alpaka/idx/MapIdx.hpp:14,
                 from /home/runner/work/alpaka/alpaka/include/alpaka/idx/bt/IdxBtOmp.hpp:18,
                 from /home/runner/work/alpaka/alpaka/include/alpaka/acc/AccCpuOmp2Threads.hpp:25,
                 from /home/runner/work/alpaka/alpaka/build/test/analysis/headerCheck/src/acc/AccCpuOmp2Threads.hpp.cpp:1:
/home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp: In static member function 'static alpaka::Vec<TDim, TVal> alpaka::traits::ReverseVec<alpaka::Vec<TDim, TVal> >::reverseVec(const alpaka::Vec<TDim, TVal>&)':
/home/runner/work/alpaka/alpaka/include/alpaka/vec/Vec.hpp:575:61: error: 'CreateReverse' is not a member of 'alpaka::traits::detail'
                 return createVecFromIndexedFn<TDim, detail::CreateReverse>(vec);
```

**Comment by j-stephan** [comment]
Now that is rather cryptic:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\functional(947): error #304: no instance of function template "std::_Invoker_ret<_Rx, false>::_Call [with _Rx=Concurrency::details::_Unit_type]" matches the argument list [D:\a\alpaka\alpaka\build\test\unit\workDiv\workDiv.vcxproj]
              argument types are: (std::decay_t<std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>>)
            detected during:
              instantiation of "_Rx std::_Func_impl_no_alloc<_Callable, _Rx, _Types...>::_Do_call(_Types &&...) [with _Callable=std::decay_t<std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>>, _Rx=Concurrency::details::_Unit_type, _Types=<>]" 
  (923): here
              instantiation of "std::_Func_impl_no_alloc<_Callable, _Rx, _Types...>::_Func_impl_no_alloc(_Other &&) [with _Callable=std::decay_t<std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>>, _Rx=Concurrency::details::_Unit_type, _Types=<>, _Other=std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>, <unnamed>=0]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\xmemory(246): here
              instantiation of "_Ty *std::_Global_new<_Ty,_Types...>(_Types &&...) [with _Ty=std::_Func_impl_no_alloc<std::decay_t<std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>>, Concurrency::details::_Unit_type>, _Types=<std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>>]" 
  (1039): here
              instantiation of "void std::_Func_class<_Ret, _Types...>::_Reset(_Fx &&) [with _Ret=Concurrency::details::_Unit_type, _Types=<>, _Fx=std::remove_reference_t<lambda []()->Concurrency::details::_Unit_type &>]" 
  (1170): here
              instantiation of "std::function<_Fty>::function(_Fx) [with _Fty=Concurrency::details::_Unit_type (), _Fx=lambda []()->Concurrency::details::_Unit_type, <unnamed>=int]" 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\ppltasks.h(2348): here
   
  1 error detected in the compilation of "D:/a/alpaka/alpaka/test/unit/workDiv/src//WorkDivHelpersTest.cpp".
```

Any insight from our Windows users what might be happening here?

@bernhardmgruber @sbastrakov @BenjaminW3

**Comment by bernhardmgruber** [comment]
Good you found that as well! I had that a week ago after a VS update. NVCC failed to parse something inside PPL (parallel patterns library), since std::future in the MS STL now uses that somewhere internally. So apparently, this could really be a recent bug. Unfortunately, I cannot recall anymore if I managed to find a workaround or just stopped on that branch in LLAMA for a while. I know it appeared for me when I used Vc and alpaka together with LLAMA. Other CUDA stuff worked fine for me on Windows. So this could also be a complicated interplay triggering this issue :S

**Comment by j-stephan** [comment]
Well, investigating this will be fun. Since none of the alpaka code in the test case directly uses `<functional>` or `std::future` this is probably something happening internally in Catch2.

**Comment by BenjaminW3** [comment]
I will remove the `required` flag from the two Windows builds. Looks like github now installs a newer Visual Studio 2019 update which broke CUDA support somehow. This is not our fault but we should still try to find a workaround.

**Review by BenjaminW3 — APPROVED** [review]

**Pull request merged**
