### PR TITLE
Update to Catch2 v3.6.0

### PR DESCRIPTION
**Pull request by sliwowitz**
See title.

Commit made with:
`git commit --author="Third Party <alpaka@hzdr.de>"`

Alternatively, should you forget to change the author while doing the commit, amend it with:
`git commit --amend --author="Third Party <alpaka@hzdr.de>" --no-message`

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
I'm confused. @mehmetyusufoglu already opened this PR: https://github.com/alpaka-group/alpaka/pull/2300

**Comment by mehmetyusufoglu** [comment]
> I'm confused. @mehmetyusufoglu already opened this PR: #2300

Ok, I am closing the one I opened... But both PRs have a compile problem with this notorious `nvcc11.1+clang9` compiler combination :)

**Comment by mehmetyusufoglu** [comment]
> See title.
> 
> Commit made with: `git commit --author="Third Party <alpaka@hzdr.de>"`
> 
> Alternatively, should you forget to change the author while doing the commit, amend it with: `git commit --amend --author="Third Party <alpaka@hzdr.de>" --no-message`

This PR can be closed i think, 3.5.2 is the current version.  Most probably after alpaka switch to c++20 we can reactivate this PR.

**Comment by psychocoderHPC** [comment]
I will close this PR because we merged https://github.com/alpaka-group/alpaka/pull/2300
@sliwowitz feel free at any time to reopen this PR.

We will soon switch to C++20 and drop the CUDA compiler 11.X anyway so maybe we should not put time into solving the nvcc bug with `__nv_bool`.

**Pull request closed without merging**
