### PR TITLE
Trim device names

### LINKED ISSUE #2187: trim device names
Some device names are padded with whitespace, _e.g._ a CPU device may return `"AMD EPYC 7763 64-Core Processor                "`.

I think removing the extra spaces makes the name less awkward to use.

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #2187

### CODE REVIEW

**Comment by SimeonEhrig** [comment]
The pipeline passed: https://gitlab.com/hzdr/crp/alpaka/-/pipelines/1080535023
Only the status was not back reported.

**Review by SimeonEhrig — APPROVED** [review]

**Comment by SimeonEhrig** [comment]
@alpaka-group/alpaka-maintainers The PR can be force merged.

**Comment by psychocoderHPC** [comment]
I forced pushed the branch again. Last week the bot was offline and this PR was pushed during this period.
The diff in gitlab was not equal to the diff in here, therefore, I did not force merge the changes.

**Review by psychocoderHPC — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
Not sure why but the tsan test is failing.

**Comment by SimeonEhrig** [comment]
@bernhardmgruber Can you please push again. Looks like Github is broken. I should be a maintainer and I cannot force merge.

**Pull request merged**
