### PR TITLE
Update CI to more recent CMake versions

### PR DESCRIPTION
**Pull request by j-stephan**
This is a preparatory PR for #921. Separate PR because #921 is quite large already. This PR removes all CMake versions < 3.15 from `.travis.yml` and updates CMake 3.15 and 3.16 to their most recent patch levels (3.15.7 and 3.16.4, respectively).

### CODE REVIEW

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by BenjaminW3** [comment]
You could also increase the `cmake_minimum_required` version in this PR but there is no need to do so.

**Comment by ax3l** [comment]
In order to avoid inconsistencies:
Ideally increase all `cmake_minimum_required` to the lowest tested number, and also update the docs in `README.md` with the new minimal version (3.15.7, I guess?).

Later on, the [spack recipe here](https://github.com/ComputationalRadiationPhysics/spack-repo/blob/gh-pages/packages/alpaka/package.py) also needs its minimal versions updated :)

**Comment by j-stephan** [comment]
Alright, all CMake files have been updated to a CMake 3.15.7+ requirement. Adapted the README.md as well.

**Review by BenjaminW3 — DISMISSED** [review]

**Review by psychocoderHPC — DISMISSED** [review]

**Review by ax3l — DISMISSED** [review]

**Comment by ax3l** [comment]
Do we have to clean the travis cache to get rid of some older `3.15.5` CMake versions?

**Comment by BenjaminW3** [comment]
This should not be necessary.
The cache is automatically reset for a specific job when something within the job description changed (e.g. env variables) . Problematic is only when we do changes to the build/install scripts which are not detected.

**Comment by BenjaminW3** [comment]
The current build issue is that we do not install CMake for Mac at all. On Mac we use the version that is already installed which seems to be 3.15.5.
The easiest fix would be to set this version as minimum in the CMake scripts.

**Review by BenjaminW3 — DISMISSED** [review]

**Comment by j-stephan** [comment]
Since there is another Mac node complaining about the CMake version (it wants 3.15.3 now) I'm considering to just set `cmake_minimum_required` to 3.15 and be done with it. The patch level shouldn't matter much anyway.

**Comment by BenjaminW3** [comment]
Sounds reasonable

**Pull request merged**
