### PR TITLE
Implement device functions to simplify writing kernel code [v2]

### PR DESCRIPTION
**Pull request by fwyzard**
Implement device functions to simplify writing kernel code:
  - `oncePerGrid(acc)`;
  - `oncePerBlock(acc)`;
  - `uniformElements(acc, size)` and `uniformElements(acc, begin, end)`;
  - `uniformGroups(acc, size)` and `uniformGroupElements(acc, group, size)`;
  - `independentGroups(acc, groups)` and `independentGroupElements(acc, group_size)`;
  - variations of these functions along different dimensions.

Implement tests for the most common functions.

### CODE REVIEW

**Comment by fwyzard** [comment]
I'm starting to hate Visual Studio...
```
D:\a\alpaka\alpaka\test\unit\exec\src\Once.cpp(133): FAILED:
  REQUIRE( *status == true )
with expansion:
  true == true
```

**Comment by fwyzard** [comment]
@psychocoderHPC all CI tests are finally happy... I can go on vacation :-)

**Review by psychocoderHPC — APPROVED** [review]

**Comment by ikbuibui** [comment]
Sorry to comment on a merged PR, was there any reason why ``makeWorkDiv()`` was put in `test/unit/exec/src`? It seems like a useful interface

**Comment by fwyzard** [comment]
The current implementation makes some assumptions on how to us thread and elements.
I have no problem moving it to a central place, but I don't know what @psychocoderHPC and @SimeonEhrig think of it.

**Comment by ikbuibui** [comment]
I noticed it also doesnt check if the work div is valid, correct? because `elements` can be greater than `maxThreadsPerBlock`

**Comment by fwyzard** [comment]
It's certainly possible.

**Pull request merged**
