### PR TITLE
Add clang-16 test runner

### LINKED ISSUE #1937: Add clang-16 to CI
clang-16 was released yesterday, we should the appropriate CI runs for it.

### PR DESCRIPTION
**Pull request by j-stephan**
Fixes #1937.

### CODE REVIEW

**Comment by j-stephan** [comment]
Looks like clang-16 is generating wrong PTX code:

```
ptxas /tmp/counterBasedRng-82eedc/counterBasedRng-sm_61.s, line 10521; fatal   : Parsing error near '.': syntax error
ptxas fatal   : Ptx assembly aborted due to errors
clang: error: ptxas command failed with exit code 255 (use -v to see invocation)
```

**Comment by bernhardmgruber** [comment]
@j-stephan, would you have some time to bring your changeset in? `icpx` was updated now and also shows these errors in tinymt:
```
/home/runner/work/alpaka/alpaka/include/alpaka/rand/TinyMT/tinymt32.h:102:9: error: unsafe buffer access [-Werror,-Wunsafe-buffer-usage]
    y = random->status[3];
        ^~~~~~~~~~~~~~
```
that this PR is fixing, and it's blocking other PRs now as well, for example: #1988. Thx!

**Comment by SimeonEhrig** [comment]
This PR fixes the readthedocs problem: https://github.com/alpaka-group/alpaka/pull/2010

**Comment by SimeonEhrig** [comment]
Actual we should merge this PR before https://github.com/alpaka-group/alpaka/pull/2005. The PR fixes also a bug in the generator script, which causes that no Clang CUDA runtime test are generated.

**Comment by SimeonEhrig** [comment]
I recommend to rebase the PR on dev and rerun the CI with [filter rule](https://alpaka.readthedocs.io/en/latest/dev/ci.html#filter-and-reorder-jobs): `CI_FILTER: ^linux_clang-cuda16`

Maybe other version than CUDA 11.3 does not work and we don't see it, because the jobs was in a later wave. With the filter rule, only 5 jobs are generated.

**Comment by j-stephan** [comment]
There is an open bug report over on the LLVM issue tracker: https://github.com/llvm/llvm-project/issues/58491 I will look into the work-around tomorrow.

**Comment by SimeonEhrig** [comment]
you need to update the requirements.txt of the job generator

**Review by SimeonEhrig — APPROVED** [review]

**Pull request merged**
