### PR TITLE
Merge adjacent traits namespaces

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This is a simple refactoring. After deleting many namespaces, we had lots of adjacent `traits` namespaces, so I merged them.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
I am not sure about this PR. The type traits namespace is somehow signalling the user that there are implementations in where he do not need aware about it. The user is mostly interacting with the "free functions".

**Comment by psychocoderHPC** [comment]
@bernhardmgruber Could you please explain why do you think it helps to remove this namespace.

**Comment by bernhardmgruber** [comment]
This PR does *not* remove any namespaces. It just merges adjacent namespaces. Thus it turns
```
namespace traits {
    ... // A
}
namespace traits {
    ... // B
}
```
into
```
namespace traits {
    ... // A
    ... // B
}
```

**Comment by sbastrakov** [comment]
Ah, I also got confused in the same way as @psychocoderHPC originally, as from a (too) brief look at github diff it felt like some `::traits` are simply removed. Thanks for explaining.

**Comment by psychocoderHPC** [comment]
> This PR does _not_ remove any namespaces. It just merges adjacent namespaces. Thus it turns
> 
> ```
> namespace traits {
>     ... // A
> }
> namespace traits {
>     ... // B
> }
> ```
> 
> into
> 
> ```
> namespace traits {
>     ... // A
>     ... // B
> }
> ```

Thanks this description, this was not obvious for me.

**Review by psychocoderHPC — APPROVED** [review]

**Pull request merged**
