### PR TITLE
Fix remaining warnings/errors with `-Werror`

### PR DESCRIPTION
**Pull request by bernhardmgruber**
This PR fixes the remaining errors when `-Werror` is turned on for the CI.

It includes supression of gcc warnings in nvcc generated code and a workaround for warnings with uninitialized `PlatformUniformCudaHipRt` analogous to #2165.

I also cherry-picked #2107 to turn on `-Werror` in the CI.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
@bernhardmgruber What kind of warnings will be fixed by this PR?

**Comment by bernhardmgruber** [comment]
> @bernhardmgruber What kind of warnings will be fixed by this PR?

The ones that break the CI of #2107. I had 10min of time and a quick look. No idea if this PR catches all. We will find out!

**Comment by bernhardmgruber** [comment]
One of the failures now is (gcc 9, nvcc 11.0):
```
/builds/hzdr/crp/alpaka/test/unit/math/src/Defines.hpp:52:35: error: left operand of comma operator has no effect [-Werror=unused-value]
   52 |                         for(size_t i = 0; i < argsItem.arity_nr; ++i)
      |                          ~~~~~~~~~^~~~~~~~~~
```
There is no comma operator here, so it is probably nvcc again generating something. I want to stop fixing such issues. We should just enable less warnings in the nvcc generated code.

Edit: I disabled the warning now.

**Review by j-stephan — APPROVED** [review]

**Comment by j-stephan** [comment]
Woohoo!

**Pull request merged**
